/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * THE BSD LICENSE
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer. 
 * Redistributions in binary form must reproduce the above copyright notice, 
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution. 
 *
 * Neither the name of the  nor the names of its contributors may be
 * used to endorse or promote products derived from this software without 
 * specific prior written permission. 
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER 
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**************************************************************************/
/* CONFIDENTIAL AND PROPRIETARY SOURCE CODE                               */
/* OF NETSCAPE COMMUNICATIONS CORPORATION                                 */
/*                                                                        */
/* Copyright © 1996,1997 Netscape Communications Corporation.  All Rights */
/* Reserved.  Use of this Source Code is subject to the terms of the      */
/* applicable license agreement from Netscape Communications Corporation. */
/*                                                                        */
/* The copyright notice(s) in this Source Code does not indicate actual   */
/* or intended publication of this Source Code.                           */
/**************************************************************************/

#define LIBRARY_NAME "httpdaemon"

static char dbthttpdaemonid[] = "$DBT: httpdaemon referenced v1 $";

#include "i18n.h"

/* Message IDs reserved for this file: CORE3000-CORE3999, HTTP3000-HTTP3999 */
BEGIN_STR(httpdaemon)
	ResDef( DBT_LibraryID_, -1, dbthttpdaemonid )/* extracted from dbthttpdaemon.h*/
	ResDef( DBT_daemonCanTLogPidToSSN_, 13, "CORE3013: can't log pid to %s (%s)" )/*extracted from daemon.cpp*/
	ResDef( DBT_warningCouldNotSetGroupIdToDSN_, 14, "CORE3014: could not set group id to %d (%s)" )/*extracted from daemon.cpp*/
	ResDef( DBT_warningCouldNotSetUserIdToDSN_, 15, "CORE3015: could not set user id to %d (%s)" )/*extracted from daemon.cpp*/
	ResDef( DBT_warningDaemonIsRunningAsSuperUse_, 16, "CORE3016: daemon is running as super-user" )/*extracted from daemon.cpp*/
	ResDef( DBT_couldNotDetermineCurrentUserName_, 17, "CORE3017: could not determine current user name" )/*extracted from daemon.cpp*/
	ResDef( DBT_errorChrootToSFailedSN_, 18, "CORE3018: chroot to %s failed (%s)" )/*extracted from daemon.cpp*/
	ResDef( DBT_DaemonNotDeadAfterTimeOut, 38, "HTTP3038: daemon not dead after %d seconds")
	ResDef( DBT_DaemonPxSessionInProgress, 39, "HTTP3039: terminating with %d sessions still in progress")
	ResDef( DBT_DaemonPxSessionCleanedUp, 40, "HTTP3040: sessions all cleaned up")
	ResDef( DBT_DaemonPxSetTerminateFlag, 41, "HTTP3041: terminating daemons")
	ResDef( DBT_DaemonPxTerminatedKeepAlives, 44, "HTTP3044: keep-alive subsystem terminated")
	ResDef( DBT_DaemonPxUXProcessArrayAllocFail, 46, "CORE3046: Could not allocate _process_array")
	ResDef( DBT_DaemonPxUXSpawnedWorkerProcess, 47, "CORE3047: Server spawned worker process %d")
	ResDef( DBT_DaemonPxUXProcessArrayOverFlow, 48, "CORE3048: Unexpected process_array overflow")
	ResDef( DBT_DaemonPxUXDetectedChildDeath, 49, "CORE3049: Detected child process %d died (status %d)")
	ResDef( DBT_DaemonPxUXWillRespawn, 50, "CORE3050: Spawning replacement for worker process %d")
	ResDef( DBT_DaemonPxUXWillNotRespawn, 51, "CORE3051: Not our child, will not spawn replacement")
	ResDef( DBT_DaemonPxUXPrimordialRecvHangup, 52, "CORE3052: Primordial process received hangup signal")
	ResDef( DBT_DaemonPxUXPrimordialSendingHangup, 53, "CORE3053: Sending SIGHUP to child %d: %d")
	ResDef( DBT_DaemonPxUXPrimordialRecvTerminationSignal, 54, "CORE3054: Primordial process received termination signal")
	ResDef( DBT_DaemonPxUXPrimordialRecvUnexpectedSignal, 56, "CORE3056: Primordial process ignoring unexpected signal %d")
	ResDef( DBT_DaemonPxUXSigHndlrThrdRecvSignal, 61, "CORE3061: received signal %d")
	ResDef( DBT_DaemonSessionKATimeOut2, 64, "HTTP3064: HTTP keep-alive timeout is %d seconds")
	ResDef( DBT_DaemonSessionKADisabled, 65, "HTTP3065: HTTP keep-alive is disabled")
	ResDef( DBT_PollManagerMaxKAConn, 66, "HTTP3066: HTTP keep-alive subsystem will accomodate up to %d connections")
	ResDef( DBT_DaemonSessionErrorRecvReq, 68, "HTTP3068: Error receiving request from %s (%s)")
	ResDef( DBT_DaemonSessionErrorAcceptConn, 69, "HTTP3069: Error accepting connection (%s)")
	ResDef( DBT_DaemonPxUXChildDiedBeforeInitComplete, 71, "CORE3071: Child died before completing init")
    /* ListenSocket error/log messages [DBT_LS prefix] */
	ResDef(DBT_LS_inform,            72, "HTTP3072: %s: %s://%s:%d %s")
	ResDef(DBT_LSReady_,             73, "ready to accept requests")
	ResDef(DBT_LSClosed_,            74, "closed")
	ResDef(DBT_LSNotClosed_, 75, "HTTP3075: %d listen socket(s) could not be closed")
        ResDef(DBT_StatsManager_TooLateToAdd, 76, "HTTP3076: Too late to add profile bucket \"%s\"")
        ResDef(DBT_StatsManager_ErrorLocking, 79, "CORE3079: Error locking stats file (%s)")
        ResDef(DBT_StatsManager_ErrorUnlocking, 80, "CORE3080: Error unlocking stats file (%s)")
        ResDef(DBT_StatsManager_TooManyVSs, 81, "HTTP3081: More than %d virtual servers are active.  Statistics will be tracked for only the first %d.")
        ResDef(DBT_StatsManager_FailedToCreateThread, 82, "CORE3082: Failed to create thread (%s)")
        ResDef(DBT_StatsManager_CouldNotMmap, 83, "CORE3083: Could not mmap stats file %s")
        ResDef(DBT_StatsManager_CouldNotOpen, 84, "CORE3084: Could not open stats file %s")
        ResDef(DBT_LogManager_ErrorLocking, 85, "HTTP3085: Error locking log file %s (%s)")
        ResDef(DBT_LogManager_ErrorUnlocking, 86, "HTTP3086: Error locking log file %s (%s)")
        ResDef(DBT_LogManager_ErrorRenaming, 87, "HTTP3087: Error renaming log file %s to %s (%s)")
        ResDef(DBT_LogManager_ErrorWriting, 88, "HTTP3088: Error writing to log file %s (%s)")
        ResDef(DBT_LogManager_PartialWrite, 89, "HTTP3089: Error writing to log file %s (%d of %d bytes written)")
        ResDef(DBT_LogManager_FailedToCreateThread, 90, "HTTP3090: Failed to create logging thread (%s)")
        ResDef(DBT_LogManager_ErrorOpening, 91, "HTTP3091: Error opening log file %s (%s)")
        ResDef(DBT_WatchDog_ErrorReceiving, 92, "CORE3092: Error receiving response from watchdog")
        ResDef(DBT_WatchDog_ErrorSending, 93, "CORE3093: Error sending request to watchdog")
	ResDef(DBT_LSNotCreated_, 94, "HTTP3094: %d listen sockets could not be created")
        ResDef(DBT_ExpiresIn, 95, "CORE3095: This beta version will expire in %d day(s)")
        ResDef(DBT_ChildAdminThread_sendEndInit, 101, "CORE3101: Error communicating with primordial process")
        ResDef(DBT_ListenSocket_closeonexec, 108, "Unable to set Close-On-Exec")
        ResDef(DBT_ListenSocket_listen, 109, "Cannot listen on socket")
        ResDef(DBT_ListenSocket_watchdogfd, 110, "Error creating socket")
        ResDef(DBT_ListenSocket_bind, 111, " Error binding to socket")
        ResDef(DBT_ListenSocket_nullconfig, 112, "Listen socket configuration is a NULL pointer")
        ResDef(DBT_ListenSocket_watchdogsocket, 113, "Error closing socket")
        ResDef(DBT_ListenSocket_close, 114, "Error closing socket")
        ResDef(DBT_ListenSocket_start_acceptor, 115, "Error starting acceptor thread")
        ResDef(DBT_ListenSocket_create_acceptor, 116, "Error creating acceptor threads")
        ResDef(DBT_ListenSocket_interrupt_acceptor, 117, "Error interrupting acceptor thread")
        ResDef(DBT_ListenSocket_null_entry_acceptor, 118, "NULL entry in acceptor table")
        ResDef(DBT_ListenSocket_malloc_acceptor, 119, "Acceptor memory allocation error")
        ResDef(DBT_ListenSocket_malloc_acceptor_table, 120, "Acceptor table memory allocation error")
        ResDef(DBT_ListenSocket_thread_created, 121, "Acceptor threads already created")
        ResDef(DBT_ListenSocket_terminate_acceptor, 122, "Acceptor thread did not terminate")
        ResDef(DBT_ListenSocket_acceptor_not_terminated, 123, "Some acceptor threads could not be terminated")
        ResDef(DBT_ListenSocket_create_socket, 124, "Error creating socket")
        ResDef(DBT_ListenSocket_unknownfailure, 126, "HTTP3126: listen socket error: %s")
        ResDef(DBT_ListenSocket_failure, 127, "HTTP3127: %s: %s://%s:%d: %s (%s)")
        ResDef(DBT_ListenSocketConfig_malloc_hash_error, 128, "Hash table memory allocation error")
        ResDef(DBT_ListenSockets_malloc, 129, "HTTP3129: Error allocating memory")
        ResDef(DBT_ListenSockets_null_config, 130, "HTTP3130: NULL configuration")
        ResDef(DBT_ListenSockets_append, 131, "HTTP3131: Cannot append LS")
        ResDef(DBT_ParentAdmin_malloc_poll, 133, "CORE3133: Error allocating admin poll array")
        ResDef(DBT_ParentAdmin_watchdog_inactive, 134, "CORE3134: Watchdog admin channel inactive")
        ResDef(DBT_ParentAdmin_init_thread, 136, "CORE3136: Error initializing admin thread")
        ResDef(DBT_ParentAdmin_exit, 138, "CORE3138: closing admin channel (%s)")
        ResDef(DBT_ParentAdmin_socket, 140, "CORE3140: error creating AF_UNIX socket for admin channel (%s)")
        ResDef(DBT_ParentAdmin_bind, 141, "CORE3141: error binding to %s (%s)")
        ResDef(DBT_ParentAdmin_listen, 142, "CORE3142: error listening on admin channel socket (%s)")
        ResDef(DBT_ParentAdmin_accept, 143, "CORE3143: Error accepting connection on admin channel")
        ResDef(DBT_ParentAdmin_channel_shutdown, 144, "CORE3144: Watchdog admin channel has been closed")
        ResDef(DBT_ParentAdmin_unknown_msg, 145, "CORE3145: Unsupported admin message %d received from watchdog")
        ResDef(DBT_ParentAdmin_primary_shutdown, 146, "CORE3146: Primary admin channel has been closed")
        ResDef(DBT_VSGroup_hash_malloc, 154, "HTTP3154: Error allocating memory for hashtable")
        ResDef(DBT_WatchDog_Reopen, 155, "CORE3155: Reopening connection to watchdog")
        ResDef(DBT_WatchDog_malloc, 156, "CORE3156: Memory allocation error")
        ResDef(DBT_WatchDog_connect, 157, "CORE3157: Could not connect to watchdog socket %s (%s)")
        ResDef(DBT_WatchDog_socket, 158, "CORE3158: Error creating AF_UNIX socket")
        ResDef(DBT_WatchDog_initfail, 159, "CORE3159: WatchdogClient incorrectly initialized")
        ResDef(DBT_WatchDog_PIDpath, 160, "CORE3160: PID path not set")
        ResDef(DBT_WatchDog_nonempty_terminate, 161, "CORE3161: received non-empty terminate response")
        ResDef(DBT_WatchDog_terminate_fail, 162, "CORE3162: error sending terminate request")
        ResDef(DBT_WatchDog_reconfig_fail, 163, "CORE3163: error sending reconfigure status")
        ResDef(DBT_WatchDog_reconfig_status_fail, 164, "CORE3164: error sending reconfigure status")
        ResDef(DBT_WebServer_watchdog_init, 167, "CORE3167: Error initializing watchdog connection")
        ResDef(DBT_WebServer_pidpath, 168, "CORE3168: Could not set PID path %s")
        ResDef(DBT_WebServer_method_registry, 169, "CORE3169: Unable to init HttpMethod Registry")
        ResDef(DBT_WebServer_config_init, 170, "CORE3170: Configuration initialization failed: %s")
        ResDef(DBT_WebServer_reopen_wd, 171, "CORE3171: Cannot reopen watchdog connection")
        ResDef(DBT_WebServer_mutex_lock, 172, "CORE3172: Cannot create server mutex critical lock")
        ResDef(DBT_WebServer_cond_var, 173, "CORE3173: Cannot create server condition variable")
        ResDef(DBT_WebServer_acl_init, 175, "HTTP3175: Late ACL initialization failed")
        ResDef(DBT_WebServer_UXSigHndlr_createthread, 176, "CORE3176: failed to create thread")
        ResDef(DBT_WebServer_nsfc_init, 177, "CORE3177: Failure initializing file cache")
        ResDef(DBT_WebServer_httpheader_init, 179, "CORE3179: Failure initializing HttpHeader")
        ResDef(DBT_WebServer_httprequest_init, 180, "CORE3180: Failure initializing HttpRequest")
        ResDef(DBT_WebServer_ds_init, 181, "CORE3181: Failure initializing DaemonSession")
        ResDef(DBT_WebServer_func_init, 182, "CORE3182: Failure initializing function execution subsystem")
        ResDef(DBT_WebServer_asyncdns_init, 183, "CORE3183: Failed to enable asynchronous DNS")
        ResDef(DBT_WebServer_invalid_conf, 185, "CORE3185: Invalid configuration: %s")
        ResDef(DBT_WebServer_set_conf, 186, "CORE3186: Failed to set configuration")
        ResDef(DBT_WebServer_late_init, 187, "CORE3187: Late initialization failed: %s")
        ResDef(DBT_WebServer_admin_thread, 188, "CORE3188: Error initializing admin thread")
        ResDef(DBT_WebServer_researt_active, 189, "CORE3189: Restart functions not called since %d sessions still active")
        ResDef(DBT_WebServer_fork, 190, "CORE3190: Error attempting to spawn child process (%s)")
        ResDef(DBT_WebServer_tmp_accessible, 192, "CORE3192: Temporary directory %s is accessible to others.  Please remove %s or choose another directory then restart the server.")
        ResDef(DBT_WebServer_tmp_writable, 193, "CORE3193: Temporary directory %s is not writable (%s)")
        ResDef(DBT_Configuration_FileNotSpecified, 197, "CORE1397: Configuration file must be specified")
        ResDef(DBT_Configuration_MissingServer, 198, "CORE3198: Missing server element")
        ResDef(DBT_Configuration_SameAddress, 199, "HTTP3199: HTTP listener %s and HTTP listener %s specify the same network address")
        ResDef(DBT_Configuration_ItemSeparator, 200, ", ")
        ResDef(DBT_Configuration_UndefinedMimeId, 203, "HTTP3203: Undefined MIME types list")
        ResDef(DBT_Configuration_CannotParseAclFile, 204, "HTTP3204: Cannot parse ACL file: ")
        ResDef(DBT_Configuration_CannotPostParseAcls, 205, "HTTP3205: Cannot postparse ACLs: ")
        ResDef(DBT_Configuration_UndefinedAclId, 206, "HTTP3206: Undefined acl ID")
        ResDef(DBT_Configuration_CannotConstructAclLists, 207, "HTTP3207: Cannot construct ACL lists")
        ResDef(DBT_Configuration_UndefinedVs, 209, "HTTP3209: Undefined virtual server")
        ResDef(DBT_Configuration_DisabledDefaultVs, 210, "HTTP3210: A disabled virtual server cannot be the default virtual server for an HTTP listener")
        ResDef(DBT_Configuration_DuplicateUrlhosts, 218, "HTTP3218: Both virtual server %s and virtual server %s specify hosts value \"%s\"")
        ResDef(DBT_Configuration_OnlyOneServerAllowed, 219, "CORE3219: Only one server element allowed")
        ResDef(DBT_Configuration_InvalidElementName, 220, "CORE3220: Invalid element name")
        ResDef(DBT_Configuration_ExpectedBooleanValue, 221, "CORE3221: Expected boolean value")
        ResDef(DBT_Configuration_ExpectedIntegralValue, 222, "CORE3222: Expected integral value")
        ResDef(DBT_Configuration_ExpectedNetworkAddress, 223, "CORE3223: Expected network address")
        ResDef(DBT_Configuration_ExpectedPort, 224, "CORE3224: Expected port")
        ResDef(DBT_Configuration_ExpectedString, 225, "CORE3225: Expected string")
        ResDef(DBT_Configuration_OutOfMemory, 227, "CORE3227: Out of memory")
        ResDef(DBT_Configuration_DatabaseNotFound, 228, "CORE3228: Database not found")
        ResDef(DBT_Configuration_QosDisabled, 229, "CORE3229: Quality of service (QOS) is disabled in the HTTP service.  Unable to turn on QOS features.")
        ResDef(DBT_Configuration_ZeroBandwidth, 230, "CORE3230: Bandwidth limit is enforced but the bandwidth limit is zero")
        ResDef(DBT_Configuration_ZeroConnections, 231, "CORE3231: Connection limit is enforced but the connection limit is zero")
        ResDef(DBT_Configuration_CannotStartBMThread, 232, "CORE3232: Unable to start Bandwidth Manager thread")
        ResDef(DBT_Configuration_DuplicateElement, 233, "CORE3233: Duplicate element")
        ResDef(DBT_Configuration_ErrorOpeningFile, 234, "CORE3234: Error opening file %s (%s)")
        ResDef(DBT_Configuration_ErrorProcessingFile, 235, "CORE3235: Error processing file %s") 
        ResDef(DBT_Configuration_BadUrlhosts, 236, "CORE3236: hosts value \"%s\" is invalid.  hosts values must not contain ")
        ResDef(DBT_Configuration_BadUrlhostsScheme, 237, "scheme identifiers (e.g. http://).")
        ResDef(DBT_Configuration_BadUrlhostsPath, 238, "path specifiers.")
        ResDef(DBT_Configuration_BadUrlhostsPort, 239, "port specifiers.")
        ResDef(DBT_Configuration_BadUrlhostsWildcard, 240, "wildcards.")
        ResDef(DBT_Configuration_QosMetricsTooSmall, 241, "CORE3241: QOS metrics interval must be at least 1 second")
        ResDef(DBT_Configuration_QosRecomputeTooSmall, 242, "CORE3242: QOS recomputation interval must be at least 10 milliseconds")
        ResDef(DBT_Configuration_InvalidFileFormat, 243, "CORE3243: Invalid file format")
        ResDef(DBT_Configuration_ErrorReadingFile, 244, "CORE3244: Error reading file")
        ResDef(DBT_Configuration_ExpectedEquals, 245, "CORE3245: Expected =")
        ResDef(DBT_Configuration_MissingClosingQuote, 246, "CORE3246: Missing closing \"")
        ResDef(DBT_Configuration_ExpectedTypeEncLangExts, 247, "CORE3247: Expected type, enc, lang, or exts")
        ResDef(DBT_Configuration_AttrMultiplyDefined, 248, "CORE3248: Attribute multiply defined")
        ResDef(DBT_Configuration_ExpectedTypeEncLang, 249, "CORE3249: Expected at least one of type, enc, or lang")
        ResDef(DBT_Configuration_ExpectedExts, 250, "CORE3250: Expected exts")
        ResDef(DBT_Configuration_ExtensionMultiplyDefined, 251, "CORE3251: Extension given multiple times")
        ResDef(DBT_Configuration_ExpectedTypeEncodingLanguage, 252, "CORE3252: Expected at least one of type, encoding, or language")
        ResDef(DBT_Configuration_ExpectedPositiveInteger, 253, "CORE3253: Expected positive integer")
        ResDef(DBT_WebServer_asyncdns_notsupp, 256, "HTTP3256: Asynchronous DNS not supported on this platform")
        ResDef(DBT_Configuration_LsHasNoSslConfig, 257, "HTTP3257: HTTP listener %s has no SSL configuration")
        ResDef(DBT_WebServer_tmp_owner, 259, "CORE3259: Temporary directory %s is not owned by the server user.  Please remove %s or choose another directory then restart the server.")
        ResDef(DBT_Crash_Signal, 260, "CORE3260: Server crash detected (signal %s)")
        ResDef(DBT_Crash_NsapiSaf, 261, "CORE3261: Crash occurred in NSAPI SAF %s")
        ResDef(DBT_Crash_FunctionAndModule, 262, "CORE3262: Crash occurred in function %s from module %s")
        ResDef(DBT_Configuration_UndefinedLs, 263, "HTTP3263: Undefined HTTP listener")
        ResDef(DBT_AsyncDNSUnsupported, 264, "CORE3264: Asynchronous DNS is not supported in this release")
        ResDef(DBT_Configuration_AddressFamilyMismatch, 265, "CORE3265: Address family mismatch")
        ResDef(DBT_UnboundVS, 266, "HTTP3266: Virtual server %s is inaccessible because it is not bound to any HTTP listener")
        ResDef(DBT_KernelStats_OpenFailed, 267, "CORE3267: Failed to open kernel statistics structures (%s)")
        ResDef(DBT_KernelStats_CloseFailed, 268, "CORE3268: Failed to close kernel statistics structures (%s)")
        ResDef(DBT_KernelStats_Inconsistency, 269, "CORE3269: Found inconsisteny in kernel statistics structures (%s)")
        ResDef(DBT_KernelStats_ReadFailed, 270, "CORE3270: Failed to read kernel statistics structures (%s)")
        ResDef(DBT_ProcessStats_OpenFailed, 271, "CORE3271: Failed to open process statistics structures (%s)")
        ResDef(DBT_ProcessStats_ReadFailed, 272, "CORE3272: Failed to read process statistics structures (%s)")
        ResDef(DBT_Configuration_MultiplyDefined, 273, "CORE3273: multiply defined")
        ResDef(DBT_successfulServerStartup_, 274, "CORE3274: successful server startup" )
        ResDef(DBT_ConfigurationManager_UnableToStartThread, 275, "CORE3275: Unable to start configuration releaser thread")
        ResDef(DBT_ConfigurationManager_InstallingNewConfiguration, 276, "CORE3276: Installing a new configuration")
        ResDef(DBT_ConfigurationManager_ConfigurationRejected, 277, "CORE3277: The new configuration was rejected, rolling back")
        ResDef(DBT_ConfigurationManager_RolledBack, 278, "CORE3278: Rolled back to the previous configuration")
        ResDef(DBT_ConfigurationManager_NotInstalled, 279, "CORE3279: New configuration not installed")
        ResDef(DBT_ConfigurationManager_SuccessfullyInstalled, 280, "CORE3280: A new configuration was successfully installed")
        ResDef(DBT_ConfigurationManager_ReleaseQueueFullNofN, 281, "CORE3281: Configuration release queue is full (%d/%d releases are pending)")
	ResDef(DBT_stdoutPrefix, 282, "CORE3282: stdout: " )
	ResDef(DBT_stderrPrefix, 283, "CORE3283: stderr: " )
        ResDef(DBT_Configuration_DisabledLs, 284, "HTTP3284: HTTP listener %s disabled")
        ResDef(DBT_Configuration_DisabledVsc, 285, "HTTP3285: virtual server class %s disabled")
        ResDef(DBT_Configuration_DisabledVs, 286, "HTTP3286: virtual server %s disabled")
        ResDef(DBT_AcceptorMaxConnections, 287, "HTTP3287: connection limit (%d) exceeded, closing socket")
        ResDef(DBT_Configuration_ErrorParsingFileLineDesc, 289, "Error parsing file %s, line %d: %s")
        ResDef(DBT_Configuration_ErrorParsingFileLineColDesc, 290, "Error parsing file %s, line %d, column %d: %s")
        ResDef(DBT_Configuration_ErrorParsingFileLineColTokenDesc, 291, "Error parsing file %s, line %d, column %d: %s: %s")
        ResDef(DBT_CouldNotDetermineServerExePath, 292, "CORE3292: Could not determine server executable path")
        ResDef(DBT_ErrorChangingToDirXBecauseY, 293, "CORE3293: Error changing to directory %s (%s)")
        ResDef(DBT_CannotDetermineCwdBecauseX, 294, "CORE3294: Cannot determine current working directory (%s)")
        ResDef(DBT_ACLInitHttpFailed, 295, "CORE3295: ACL initialization failed")
        ResDef(DBT_CannotFindUserX, 296, "CORE3296: Cannot find user %s")
        ResDef(DBT_ErrorProcessingTagXPrefix, 297, "Error processing <%s> element: ")
        ResDef(DBT_CannotExportServerPathX, 298, "Error exporting server library path %s")
        ResDef(DBT_Configuration_ErrorSubstitutingFileReason, 299, "CORE3299: Error substituting variables in file %s (%s)") 
        ResDef(DBT_Scheduler_TimeJumpForwardXToY, 300, "CORE3300: Some scheduled events may have been skipped (Time jumped forward from %s to %s)")
        ResDef(DBT_Scheduler_TimeJumpBackwardXToY, 301, "CORE3301: Temporarily suspending event scheduling (Time jumped backward from %s to %s)")
        ResDef(DBT_Scheduler_TimeCaughtUp, 302, "CORE3302: Resuming event scheduling")
        ResDef(DBT_Scheduler_LogSuffixXConflict, 303, "CORE3303: Skipping log rotation following DST change (Archived log files with \"%s\" suffix would be overwritten)")
        ResDef(DBT_Scheduler_ServerReconfig, 304, "CORE3304: Performing scheduled server reconfiguration")
        ResDef(DBT_Scheduler_ServerRestart, 305, "CORE3305: Performing scheduled server restart")
        ResDef(DBT_Scheduler_CannotExecXReasonY, 306, "CORE3306: Event scheduler cannot execute %s (%s)")
        ResDef(DBT_Scheduler_CannotCreateThreadReasonX, 307, "CORE3307: Event scheduler failed to create thread (%s)")
        ResDef(DBT_Scheduler_RotatingAccess, 308, "CORE3308: Rotating access log files")
        ResDef(DBT_Scheduler_RotatingError, 309, "CORE3309: Rotating server log files")
        ResDef(DBT_ParentAdmin_path_too_long, 310, "CORE3310: Error binding to %s (Temporary directory path too long)")
        ResDef(DBT_ParentAdmin_connect, 311, "CORE3311: Error connecting to admin channel (%s)")
        ResDef(DBT_Reconfigure_ChangesNotApplied, 312, "CORE3312: Some configuration changes were not applied (%s)")
        ResDef(DBT_Reconfigure_ChangesIncompatible, 313, "CORE3313: The new configuration is incompatible with the existing configuration (%s)")
        ResDef(DBT_Reconfigure_FileXRestart, 314, "%s changes require a server restart")
        ResDef(DBT_Reconfigure_LoggingRestart, 315, "Logging changes require a server restart")
        ResDef(DBT_Reconfigure_PlatformRestart, 316, "Platform changes require a server restart")
        ResDef(DBT_Reconfigure_UserRestart, 317, "User changes require a server restart")
        ResDef(DBT_Reconfigure_TempPathRestart, 318, "Temporary directory changes require a server restart")
        ResDef(DBT_Reconfigure_ACLCacheRestart, 319, "ACL cache changes require a server restart")
        ResDef(DBT_Reconfigure_HTTPRestart, 320, "HTTP protocol changes require a server restart")
        ResDef(DBT_Reconfigure_KeepAliveRestart, 321, "Connection keep-alive changes require a server restart")
        ResDef(DBT_Reconfigure_ThreadPoolRestart, 322, "Thread pool changes require a server restart")
        ResDef(DBT_Reconfigure_PKCS11Restart, 323, "PKCS #11 changes require a server restart")
        ResDef(DBT_Reconfigure_EnablingSSLRestart, 324, "Enabling PKCS #11 or SSL requires a server restart")
        ResDef(DBT_Reconfigure_StatsRestart, 325, "Statistics collection changes require a server restart")
        ResDef(DBT_Reconfigure_CGIRestart, 326, "CGI changes require a server restart")
        ResDef(DBT_Reconfigure_DNSRestart, 327, "DNS changes require a server restart")
        ResDef(DBT_Reconfigure_FileCacheRestart, 328, "File cache changes require a server restart")
        ResDef(DBT_Reconfigure_SSLSessionCacheRestart, 329, "SSL/TLS session cache changes require a server restart")
        ResDef(DBT_Reconfigure_AccessLogBufferRestart, 330, "Access log buffering changes require a server restart")
        ResDef(DBT_Reconfigure_JVMRestart, 331, "JVM changes require a server restart")
        ResDef(DBT_Configuration_ObsoleteFile, 332, "CORE3332: Obsolete configuration file %s ignored")
        ResDef(DBT_WebServer_dns_cache_init, 333, "CORE3333: Failure initializing DNS cache")
        ResDef(DBT_Configuration_CannotInitAuthDb, 334, "HTTP3334: Cannot initialize authentication database: ")
        ResDef(DBT_ParentStats_CloseConnection, 335, "CORE3335: Closing stats connection for child %d")
        ResDef(DBT_ParentStats_IgnoredReconfigure, 336, "CORE3336: stats: ignoring reconfigure changes")
        ResDef(DBT_ParentStats_InternalError, 337, "CORE3337: Internal stats communication error in %s for child %d")
        ResDef(DBT_StatsServerMessage_InternalError, 338, "CORE3338: Internal stats messaging error")
        ResDef(DBT_NTStatsServer_ErrorChannelCreation, 339, "CORE3339: Error in creating stats channel")
        ResDef(DBT_CRL_OOM_cache, 340, "CORE3340: update-crl: Out of memory: Unable to cache CRL from [%s]")
        ResDef(DBT_CRL_OOM_dir, 341, "CORE3341: update-crl: Out of memory: Cannot read files")
        ResDef(DBT_CRL_read_err, 342, "CORE3342: update-crl: Error accessing [%s]")
        ResDef(DBT_CRL_OOM_file, 343, "CORE3343: update-crl: Out of memory: Cannot read file [%s]")
        ResDef(DBT_CRL_remove, 344, "CORE3344: update-crl: Removing CRL corresponding to [%s]")
        ResDef(DBT_CRL_fail_remove, 345, "CORE3345: update-crl: Unable to remove CRL (error %d); CRL processing may be corrupted")
        ResDef(DBT_CRL_adding, 346, "CORE3346: update-crl: Loading new CRL from [%s]")
        ResDef(DBT_CRL_cache, 347, "CORE3347: update-crl: Unable to cache CRL from [%s], verify whether it is valid (error %d)")
        ResDef(DBT_CRL_update, 348, "CORE3348: update-crl: Updating CRL from [%s]")
        ResDef(DBT_CRL_hashinit, 349, "CORE3349: update-crl: Unable to initialize hashtable")
        ResDef(DBT_CRL_nonssdb, 350, "CORE3350: update-crl: Unable to access NSS db")
        ResDef(DBT_CRL_baddir, 351, "CORE3351: update-crl: Unable to read dir [%s]")
        ResDef(DBT_DaemonSession_ThreadXOfYError, 352, "CORE3352: Error creating request-processing thread %d of %d (%s)")
        ResDef(DBT_Reconfigure_SecmodDbRestart, 353, "PKCS #11 module changes require a server restart")
        ResDef(DBT_Reconfigure_TrustDbRestart, 354, "Certificate/key trust database changes require a server restart")
        ResDef(DBT_Reconfigure_ClusterRestart, 355, "Cluster changes require a server restart")
        ResDef(DBT_Reconfigure_SessionReplicationRestart, 356, "Session replication changes require a server restart")
        ResDef(DBT_Platform_UnsupportedBitiness, 357, "CORE3357: The server is configured to run as a %d-bit process, but only %d-bit support is available")
        ResDef(DBT_Configuration_CannotParseConfigFile, 358, "HTTP3358: Cannot parse the configuration file")
        ResDef(DBT_Configuration_UnsupportedFeatureBeingUsed, 359, "HTTP3359: An unsupported element %s is being used. The server may not operate correctly if unsupported features are used.")
        ResDef(DBT_ConnectionOverflow, 360, "HTTP3360: connection limit (%d) exceeded.")
        ResDef(DBT_LackOfAvailableFileDescriptors, 361, "CORE3361: Insufficient file descriptors for optimum configuration.")
END_STR(httpdaemon)
