/**************************************************************************/
/* CONFIDENTIAL AND PROPRIETARY SOURCE CODE                               */
/* OF NETSCAPE COMMUNICATIONS CORPORATION                                 */
/*                                                                        */
/* Copyright © 1996,1997 Netscape Communications Corporation.  All Rights */
/* Reserved.  Use of this Source Code is subject to the terms of the      */
/* applicable license agreement from Netscape Communications Corporation. */
/*                                                                        */
/* The copyright notice(s) in this Source Code does not indicate actual   */
/* or intended publication of this Source Code.                           */
/**************************************************************************/

#define LIBRARY_NAME "base"

static char dbtbaseid[] = "$DBT: base referenced v1 $";

#include "i18n.h"

/* Message IDs reserved for this file: CORE1000-CORE1999 */
BEGIN_STR(base)
	ResDef( DBT_LibraryID_, -1, dbtbaseid )/* extracted from dbtbase.h*/
	ResDef( DBT_insufficientMemoryToCreateHashTa_, 1, "CORE1001: insufficient memory to create hash table" )/*extracted from cache.cpp*/
	ResDef( DBT_insufficientMemoryToCreateHashTa_1, 2, "CORE1002: insufficient memory to create hash table" )/*extracted from cache.cpp*/
	ResDef( DBT_cacheDestroyCacheTablesAppearCor_, 3, "CORE1003: cache_destroy: cache tables appear corrupt." )/*extracted from cache.cpp*/
	ResDef( DBT_unableToAllocateHashEntry_, 4, "CORE1004: unable to allocate hash entry" )/*extracted from cache.cpp*/
	ResDef( DBT_cacheInsertUnableToCreateCacheEn_, 5, "CORE1005: cache_insert: unable to create cache entry" )/*extracted from cache.cpp*/
	ResDef( DBT_http10200OkNcontentTypeTextHtmlN_, 6, "HTTP/1.0 200 OK\nContent-type: text/html\n\n" )/*extracted from cache.cpp*/
	ResDef( DBT_H2NetscapeCacheStatusReportH2N_, 7, "<H2>Server cache status report</H2>\n" )/*extracted from cache.cpp*/
	ResDef( DBT_noCachesOnSystemP_, 8, "No caches on system<P>" )/*extracted from cache.cpp*/
	ResDef( DBT_H2SCacheH2N_, 9, "<H2>%s cache</H2>\n" )/*extracted from cache.cpp*/
	ResDef( DBT_cacheHitRatioDDFPNPN_, 10, "Cache hit ratio: %d/%d (%f)</P>\n</P>\n" )/*extracted from cache.cpp*/
	ResDef( DBT_cacheSizeDDPNPN_, 11, "Cache size: %d/%d</P>\n</P>\n" )/*extracted from cache.cpp*/
	ResDef( DBT_hashTableSizeDPNPN_, 12, "Hash table size: %d</P>\n</P>\n" )/*extracted from cache.cpp*/
	ResDef( DBT_mruDPNlruDPN_, 13, "mru       : %d</P>\nlru       : %d</P>\n" )/*extracted from cache.cpp*/
	ResDef( DBT_UlTableBorder4ThBucketThThAddres_, 14, "<UL><TABLE BORDER=4> <TH>Bucket</TH> <TH>Address</TH> <TH>Key</TH> <TH>Access Count</TH> <TH>Delete</TH> <TH>Next</TH> <TH>LRU</TH> <TH>MRU</TH> <TH>Data</TH>\n" )/*extracted from cache.cpp*/
	ResDef( DBT_munmapFailedS_, 15, "CORE1015: munmap failed (%s)" )/*extracted from buffer.cpp*/
	ResDef( DBT_munmapFailedS_1, 16, "CORE1016: munmap failed (%s)" )/*extracted from buffer.cpp*/
	ResDef( DBT_closeFailedS_, 17, "CORE1017: close failed (%s)" )/*extracted from buffer.cpp*/
        ResDef( DBT_Waitpid_Failed, 96, "CORE1096: waitpid failed for pid %d: errno = %d %s")
        ResDef( DBT_Waitpid_Returned, 97, "CORE1097: waitpid returned 0 for pid %d: errno = %d %s")
	ResDef( DBT_dnsCacheInsertErrorAllocatingEnt_, 113, "CORE1113: dns-cache-insert: Error allocating entry" )/*extracted from dns_cache.cpp*/
	ResDef( DBT_dnsCacheInsertMallocFailure_, 114, "CORE1114: dns-cache-insert: malloc failure" )/*extracted from dns_cache.cpp*/
	ResDef( DBT_SBS_, 116, "CORE1116: %s" )/*extracted from ereport.cpp*/
	ResDef( DBT_netscapeExecutableAndSharedLibra_, 117, "CORE1117: Server executable and shared library have different versions" )/*extracted from ereport.cpp*/
	ResDef( DBT_executableVersionIsS_, 118, "CORE1118:   executable version is %s" )/*extracted from ereport.cpp*/
	ResDef( DBT_sharedLibraryVersionIsS_, 119, "CORE1119:   shared library version is %s" )/*extracted from ereport.cpp*/
	ResDef( DBT_warning_, 121, "warning" )/*extracted from ereport.cpp*/
	ResDef( DBT_config_, 122, "config" )/*extracted from ereport.cpp*/
	ResDef( DBT_security_, 123, "security" )/*extracted from ereport.cpp*/
	ResDef( DBT_failure_, 124, "failure" )/*extracted from ereport.cpp*/
	ResDef( DBT_catastrophe_, 125, "catastrophe" )/*extracted from ereport.cpp*/
	ResDef( DBT_info_, 126, "info" )/*extracted from ereport.cpp*/
	ResDef( DBT_verbose_, 127, "fine" )/*extracted from ereport.cpp*/
	ResDef( DBT_eventHandlerFailedToWaitOnEvents_, 128, "CORE1128: event_handler:Failed to wait on events %s" )/*extracted from eventhandler.cpp*/
	ResDef( DBT_couldNotWaitOnResumeEventEventS_, 129, "CORE1129: could not wait on resume event event  (%s)" )/*extracted from eventhandler.cpp*/
	ResDef( DBT_dlopenOfSFailedS_, 130, "CORE1130: dlopen of %s failed (%s)" )/*extracted from LibMgr.cpp*/
	ResDef( DBT_dlopenOfSFailedS_1, 131, "CORE1131: dlopen of %s failed (%s)" )/*extracted from LibMgr.cpp*/
	ResDef( DBT_pipebufBuf2sdPipebufGrabIoErrorD_, 168, "CORE1168: pipebuf_buf2sd: pipebuf_grab IO_ERROR %d" )/*extracted from ntpipe.cpp*/
	ResDef( DBT_poolInitInternalAllocatorDisabled_, 169, "CORE1169: pool-init: internal memory pool allocator disabled" )/*extracted from pool.cpp*/
	ResDef( DBT_poolInitFreeSize0UsingD_, 170, "CORE1170: pool-init: free_size <= 0, using %d" )/*extracted from pool.cpp*/
	ResDef( DBT_poolCreateBlockOutOfMemory_, 171, "CORE1171: pool-create-block: out of memory" )/*extracted from pool.cpp*/
	ResDef( DBT_poolCreateOutOfMemory_, 172, "CORE1172: pool-create: out of memory" )/*extracted from pool.cpp*/
	ResDef( DBT_poolCreateOutOfMemory_1, 173, "CORE1173: pool-create: out of memory" )/*extracted from pool.cpp*/
	ResDef( DBT_poolMallocOutOfMemory_, 174, "CORE1174: pool-malloc: out of memory" )/*extracted from pool.cpp*/
	ResDef( DBT_regexErrorSRegexS_, 176, "CORE1176: Invalid regular expression: %s (%s)" )
	ResDef( DBT_couldNotRemoveTemporaryDirectory_, 204, "CORE1204: Could not remove temporary directory %s,  Error %d" )/*extracted from util.cpp*/
	ResDef( DBT_couldNotRemoveTemporaryDirectory_1, 205, "CORE1205: Could not remove temporary directory %s, Error %d" )/*extracted from util.cpp*/
	ResDef( DBT_netAcceptEnter, 222, "CORE1222: Sem_grab failed (%s)")
	ResDef( DBT_netAcceptExit, 223, "CORE1223: Sem_release failed (%s)")
	ResDef( DBT_servNSSTerminatingService, 224, "CORE1224: Terminating service: %s\n")
	ResDef( DBT_servNSSSSLv2OnWithoutCiphers, 225, "CORE1225: SSLv2 is on, but no SSLv2 ciphers are enabled. SSLv2 connections will fail.")
	ResDef( DBT_servNSSSSLv3OnWithoutCiphers, 226, "CORE1226: SSLv3 is on, but no SSLv3 ciphers are enabled. SSLv3 connections will fail.")
	ResDef( DBT_servNSSPKCS11InitFailed, 227, "CORE1227: NSS PKCS #11 initialization failed (%s)")
	ResDef( DBT_servNSSSetDomesticFailed, 228, "CORE1228: NSS Set domestic policy failed: %d")
	ResDef( DBT_servNSSSetFrenchFailed, 229, "CORE1229: NSS Set French policy failed: %d")
	ResDef( DBT_servNSSSetExportFailed, 230, "CORE1230: NSS Set Export policy failed: %d")
	ResDef( DBT_servNSSClientAuthMisconfig, 231, "CORE1231: SSL v3 must be enabled to use SSLClientAuth")
	ResDef( DBT_servNSSNoCiphers, 232, "CORE1232: Security is on, but SSLv2, SSLv3 and TLS are all off. SSL/TLS connections will fail.")
	ResDef( DBT_servNSSPKCS11PinError, 233, "CORE1233: Error setting PKCS #11 PIN: %s")
	ResDef( DBT_servNSSExpiredCert, 234, "CORE1234: SSL server certificate %s is expired.")
	ResDef( DBT_servNSSCertNotValidYet, 235, "CORE1235: SSL server certificate %s is not yet valid.")
	ResDef( DBT_servNSSErrorSecureServerConfig, 236, "CORE1236: SSL error configuring server: %s")
	ResDef( DBT_servNSSHandshakeCallbackConfigureError, 237, "CORE1237: SSL error configuring handshake callback: %s")
	ResDef( DBT_servNSSSSLWarning, 240, "CORE1240: SSL_Warning: %s")
	ResDef( DBT_systemReallocSmallerSize, 241, "CORE1241: realloc: attempt to realloc to smaller size")
	ResDef( DBT_systemRFreeCorruptMemoryPre, 242, "CORE1242: free: corrupt memory (prebounds overwrite)")
	ResDef( DBT_systemRFreeCorruptMemoryPost, 243, "CORE1243: free: corrupt memory (postbounds overwrite)")
	ResDef( DBT_systemRFreeUnallocatedMem, 244, "CORE1244: free: freeing unallocated memory")
	ResDef( DBT_servNSSTLSOnWithoutCiphers, 245, "CORE1245: TLS is on, but no TLS ciphers are enabled. TLS connections will fail.")
	ResDef( DBT_notSupportedInThisRelease, 246, "CORE1246: %s is not supported in this release.") /* extracted from cinfo.cpp */
	ResDef( DBT_servNSSnoPassfromWD, 247, "CORE1247: getting a SSL password from WD failed.") /* extracted from servnss.cpp */
	ResDef( DBT_servNSSVirtualNoUrlhostSubjectMatch, 250, "CORE1250: In secure virtual server %s, host %s does not match subject %s of certificate %s.") /* extracted from sslconf.cpp */
	ResDef( DBT_servNSSGroupNoServernameSubjectMatch, 251, "CORE1251: On HTTP listener %s, server name %s does not match subject \"%s\" of certificate %s.") /* extracted from sslconf.cpp */
	ResDef( DBT_servNSSSSL2ProtocolDisabled, 252, "CORE1252: The SSL2 protocol is disabled, yet SSL2 ciphers were specified. Ignoring the following ciphers: %s") /* extracted from sslconf.cpp */
	ResDef( DBT_servNSSSSL3TLSProtocolDisabled, 253, "CORE1253: The SSL3 and TLS protocols are disabled, yet SSL3/TLS ciphers were specified. Ignoring the following ciphers: %s") /* extracted from sslconf.cpp */
	ResDef( DBT_GetHttpdObjsetCalledOutsideVS, 254, "CORE1254: NSAPI plugin called vs_get_httpd_objset outside of VSInitFunc/VSDestroyFunc processing") /* extracted from vs.cpp */
	ResDef( DBT_GetDefaultHttpdObjsetCalledOutsideVS, 255, "CORE1255: NSAPI plugin called vs_get_default_httpd_objset outside of VSInitFunc/VSDestroyFunc processing") /* extracted from vs.cpp */
	ResDef( DBT_servNSSdbnopassword, 256, "CORE1256: The server key database has not been initialized")
	ResDef( DBT_servNSStokenuninitialized, 257, "CORE1257: The token \"%s\" has not been initialized")
        ResDef( DBT_nocoredump, 258, "CORE1258: Failed to disable core dumps (%s)")
        ResDef( DBT_certnotfound, 259, "CORE1259: unable to find certificate %s")
        ResDef( DBT_keynotfound, 260, "CORE1260: unable to find a key for certificate %s")
        ResDef( DBT_badcipherstring, 261, "CORE1261: invalid cipher string %s. Format is +cipher1,-cipher2...")
        ResDef( DBT_badcipher, 262, "CORE1262: The cipher %s is not a valid cipher for this protocol")
        ResDef( DBT_unknowncipher, 263, "CORE1263: Unknown cipher: %s")
        ResDef( DBT_badsslparams, 265, "CORE1265: Error setting SSL parameters for HTTP listener")
        ResDef( DBT_slotnotfound, 266, "CORE1266: Unable to find slot %s for certificate %s")
        ResDef( DBT_outofmemory, 267, "CORE1267: out of memory")
        ResDef( DBT_securityoff, 268, "CORE1268: SSL/TLS cannot be enabled because PKCS #11 was explicitly disabled")
        ResDef( DBT_system_errmsg_outofmemory, 269, "out of memory")
        ResDef( DBT_system_errmsg_unknownerror, 270, "unknown error %d")
        ResDef( DBT_invalidshexp, 271, "invalid shell expression")
        ResDef( DBT_finer_, 272, "finer")
        ResDef( DBT_finest_, 273, "finest")
        ResDef( DBT_ereportFunctionUnsupported, 274, "CORE1274: %s is not supported in this release")
        ResDef( DBT_ereportErrorOpeningErrorLog, 275, "CORE1275: error opening error log %s (%s)")
        ResDef( DBT_ereportErrorReopeningErrorLog, 276, "CORE1276: error reopening error log %s (%s)")
        ResDef( DBT_ereportErrorRenamingErrorLog, 277, "CORE1277: error renaming error log %s to %s (%s)")
        ResDef( DBT_LineXTooLong, 278, "line %d too long")
        ResDef( DBT_maxVarDepthX, 279, "Exceeded maximum of %d nested variables")
        ResDef( DBT_varLoopFromXToY, 280, "Circular reference from $%s to $%s")
        ResDef( DBT_undefinedVarX, 281, "Undefined variable $%s")
        ResDef( DBT_badFragmentLenXStrY, 282, "Undefined variable %.*s")
        ResDef( DBT_tokenXPINPrompt, 283, "Please enter the PIN for the \"%s\" token: ")
        ResDef( DBT_tokenXPINIncorrect, 284, "The PIN specified for the \"%s\" token is incorrect.")
	ResDef( DBT_servNSSInitFailed, 285, "CORE1285: NSS initialization failed (%s)")
        ResDef( DBT_servNSSPINDlgError, 286, "CORE1286: Error prompting for PKCS #11 token PIN (Service may not be allowed to interact with desktop)")
        ResDef( DBT_servNSSPINWriteProcessMemoryError, 287, "CORE1287: Error writing PIN to shared memory")
        ResDef( DBT_tooManyCerts, 288, "CORE1288: Too many server certificates, installing only first %d")
        ResDef( DBT_unknownKEAType, 289, "CORE1289: Unknown cert KEA type (%d)")
        ResDef( DBT_badCiphersuite, 290, "CORE1290: Cipher suite %s is not supported (%s)")
        ResDef( DBT_suchWeakCipher, 291, "CORE1291: Weak cipher suite %s is enabled")
        ResDef (DBT_unknownCertType, 292, "CORE1292: Cert type required for cipher suite %s is unknown, the server may be unable to service SSL/TLS requests")
        ResDef( DBT_wantECCnoECC, 293, "CORE1293: Server has only ECC cert(s) but no suitable cipher suites are enabled. Enable some ECC cipher suites.")
        ResDef( DBT_wantRSAnoRSA, 294, "CORE1294: Server has only RSA cert(s) but no suitable cipher suites are enabled. Enable some RSA cipher suites.")
        ResDef( DBT_cannotBypass, 295, "CORE1295: PKCS#11 bypass has been disabled because the current configuration cannot support bypass")
        ResDef( DBT_nickCantBypass, 296, "CORE1296: Token associated with server certificate [%s] cannot support PKCS#11 bypass")
    
        /* DBT_nspr_errors_ */
        ResDef( DBT_nspr_errors_0, 1000, "Out of memory" )
        ResDef( DBT_nspr_errors_1, 1001, "Bad file descriptor" )
        ResDef( DBT_nspr_errors_2, 1002, "Data temporarily not available" )
        ResDef( DBT_nspr_errors_3, 1003, "Access fault" )
        ResDef( DBT_nspr_errors_4, 1004, "Invalid method" )
        ResDef( DBT_nspr_errors_5, 1005, "Illegal access" )
        ResDef( DBT_nspr_errors_6, 1006, "Unknown error" )
        ResDef( DBT_nspr_errors_7, 1007, "Pending interrupt" )
        ResDef( DBT_nspr_errors_8, 1008, "Not implemented" )
        ResDef( DBT_nspr_errors_9, 1009, "IO error" )
        ResDef( DBT_nspr_errors_10, 1010, "IO timeout error" )
        ResDef( DBT_nspr_errors_11, 1011, "IO already pending error" )
        ResDef( DBT_nspr_errors_12, 1012, "Directory open error" )
        ResDef( DBT_nspr_errors_13, 1013, "Invalid Argument" )
        ResDef( DBT_nspr_errors_14, 1014, "Address not available" )
        ResDef( DBT_nspr_errors_15, 1015, "Address not supported" )
        ResDef( DBT_nspr_errors_16, 1016, "Already connected" )
        ResDef( DBT_nspr_errors_17, 1017, "Bad address" )
        ResDef( DBT_nspr_errors_18, 1018, "Address already in use" )
        ResDef( DBT_nspr_errors_19, 1019, "Connection refused" )
        ResDef( DBT_nspr_errors_20, 1020, "Network unreachable" )
        ResDef( DBT_nspr_errors_21, 1021, "Connection timed out" )
        ResDef( DBT_nspr_errors_22, 1022, "Not connected" )
        ResDef( DBT_nspr_errors_23, 1023, "Load library error" )
        ResDef( DBT_nspr_errors_24, 1024, "Unload library error" )
        ResDef( DBT_nspr_errors_25, 1025, "Find symbol error" )
        ResDef( DBT_nspr_errors_26, 1026, "Insufficient resources" )
        ResDef( DBT_nspr_errors_27, 1027, "Directory lookup error" )
        ResDef( DBT_nspr_errors_28, 1028, "Invalid thread private data key" )
        ResDef( DBT_nspr_errors_29, 1029, "PR_PROC_DESC_TABLE_FULL_ERROR: file descriptor table full" )
        ResDef( DBT_nspr_errors_30, 1030, "PR_SYS_DESC_TABLE_FULL_ERROR: file descriptor table full" )
        ResDef( DBT_nspr_errors_31, 1031, "Descriptor is not a socket" )
        ResDef( DBT_nspr_errors_32, 1032, "Descriptor is not a TCP socket" )
        ResDef( DBT_nspr_errors_33, 1033, "Socket address is already bound" )
        ResDef( DBT_nspr_errors_34, 1034, "No access rights" )
        ResDef( DBT_nspr_errors_35, 1035, "Operation not supported" )
        ResDef( DBT_nspr_errors_36, 1036, "Protocol not supported" )
        ResDef( DBT_nspr_errors_37, 1037, "Remote file error" )
        ResDef( DBT_nspr_errors_38, 1038, "Buffer overflow error" )
        ResDef( DBT_nspr_errors_39, 1039, "Connection reset by peer" )
        ResDef( DBT_nspr_errors_40, 1040, "Range error" )
        ResDef( DBT_nspr_errors_41, 1041, "Deadlock error" )
        ResDef( DBT_nspr_errors_42, 1042, "File is locked" )
        ResDef( DBT_nspr_errors_43, 1043, "File is too big" )
        ResDef( DBT_nspr_errors_44, 1044, "No space on device" )
        ResDef( DBT_nspr_errors_45, 1045, "Pipe error" )
        ResDef( DBT_nspr_errors_46, 1046, "No seek on device" )
        ResDef( DBT_nspr_errors_47, 1047, "File is a directory" )
        ResDef( DBT_nspr_errors_48, 1048, "Loop error" )
        ResDef( DBT_nspr_errors_49, 1049, "Name too long" )
        ResDef( DBT_nspr_errors_50, 1050, "File not found" )
        ResDef( DBT_nspr_errors_51, 1051, "File is not a directory" )
        ResDef( DBT_nspr_errors_52, 1052, "Read-only filesystem" )
        ResDef( DBT_nspr_errors_53, 1053, "Directory not empty" )
        ResDef( DBT_nspr_errors_54, 1054, "Filesystem mounted" )
        ResDef( DBT_nspr_errors_55, 1055, "Not same device" )
        ResDef( DBT_nspr_errors_56, 1056, "Directory corrupted" )
        ResDef( DBT_nspr_errors_57, 1057, "File exists" )
        ResDef( DBT_nspr_errors_58, 1058, "Maximum directory entries" )
        ResDef( DBT_nspr_errors_59, 1059, "Invalid device state" )
        ResDef( DBT_nspr_errors_60, 1060, "Device is locked" )
        ResDef( DBT_nspr_errors_61, 1061, "No more files" )
        ResDef( DBT_nspr_errors_62, 1062, "End of file" )
        ResDef( DBT_nspr_errors_63, 1063, "File seek error" )
        ResDef( DBT_nspr_errors_64, 1064, "File is busy" )
        ResDef( DBT_nspr_errors_65, 1065, "NSPR error 65" )
        ResDef( DBT_nspr_errors_66, 1066, "In progress error" )
        ResDef( DBT_nspr_errors_67, 1067, "Already initiated" )
        ResDef( DBT_nspr_errors_68, 1068, "Group empty" )
        ResDef( DBT_nspr_errors_69, 1069, "Invalid state" )
        ResDef( DBT_nspr_errors_70, 1070, "Network down" )
        ResDef( DBT_nspr_errors_71, 1071, "Socket shutdown" )
        ResDef( DBT_nspr_errors_72, 1072, "Connect aborted" )
        ResDef( DBT_nspr_errors_73, 1073, "Host unreachable" )
        ResDef( DBT_nspr_errors_74, 1074, "Library not loaded" )
        ResDef( DBT_nspr_errors_75, 1075, "The one-time function was previously called and failed. Its error code is no longer available" )

        /* DBT_libsec_errors: http://www.mozilla.org/projects/security/pki/nss/ref/ssl/sslerr.html */
        ResDef( DBT_libsec_errors_0, 2000, "SEC_ERROR_IO: I/O error during authentication or crypto operation." )
        ResDef( DBT_libsec_errors_1, 2001, "SEC_ERROR_LIBRARY_FAILURE: Library failure." )
        ResDef( DBT_libsec_errors_2, 2002, "SEC_ERROR_BAD_DATA: Bad data was received." )
        ResDef( DBT_libsec_errors_3, 2003, "SEC_ERROR_OUTPUT_LEN: Output length error." )
        ResDef( DBT_libsec_errors_4, 2004, "SEC_ERROR_INPUT_LEN: Input length error." )
        ResDef( DBT_libsec_errors_5, 2005, "SEC_ERROR_INVALID_ARGS: Invalid arguments." )
        ResDef( DBT_libsec_errors_6, 2006, "SEC_ERROR_INVALID_ALGORITHM: Certificate contains invalid encryption or signature algorithm." )
        ResDef( DBT_libsec_errors_7, 2007, "SEC_ERROR_INVALID_AVA: Invalid AVA." )
        ResDef( DBT_libsec_errors_8, 2008, "SEC_ERROR_INVALID_TIME: Certificate contains an invalid time value." )
        ResDef( DBT_libsec_errors_9, 2009, "SEC_ERROR_BAD_DER: Improper DER encoding." )
        ResDef( DBT_libsec_errors_10, 2010, "SEC_ERROR_BAD_SIGNATURE: Client certificate has invalid signature." )
        ResDef( DBT_libsec_errors_11, 2011, "SEC_ERROR_EXPIRED_CERTIFICATE: Client certificate has expired." )
        ResDef( DBT_libsec_errors_12, 2012, "SEC_ERROR_REVOKED_CERTIFICATE: Client certificate has been revoked." )
        ResDef( DBT_libsec_errors_13, 2013, "SEC_ERROR_UNKNOWN_ISSUER: Client certificate is signed by an unknown issuer." )
        ResDef( DBT_libsec_errors_14, 2014, "SEC_ERROR_BAD_KEY: Client certificate contains an invalid public key." )
        ResDef( DBT_libsec_errors_15, 2015, "SEC_ERROR_BAD_PASSWORD: Security password entered is incorrect." )
        ResDef( DBT_libsec_errors_16, 2016, "SEC_ERROR_RETRY_PASSWORD: Password entered incorrectly." )
        ResDef( DBT_libsec_errors_17, 2017, "SEC_ERROR_NO_NODELOCK: No nodelock." )
        ResDef( DBT_libsec_errors_18, 2018, "SEC_ERROR_BAD_DATABASE: Problem using certificate or key database." )
        ResDef( DBT_libsec_errors_19, 2019, "SEC_ERROR_NO_MEMORY: Out of memory." )
        ResDef( DBT_libsec_errors_20, 2020, "SEC_ERROR_UNTRUSTED_ISSUER: Client certificate is signed by an untrusted issuer." )
        ResDef( DBT_libsec_errors_21, 2021, "SEC_ERROR_UNTRUSTED_CERT: Client certificate has been marked as not trusted." )
        ResDef( DBT_libsec_errors_22, 2022, "SEC_ERROR_DUPLICATE_CERT: Certificate already exists in your database." )
        ResDef( DBT_libsec_errors_23, 2023, "SEC_ERROR_DUPLICATE_CERT_TIME: Downloaded certificate's name duplicates one already in your database." )
        ResDef( DBT_libsec_errors_24, 2024, "SEC_ERROR_ADDING_CERT: Error adding certificate to database." )
        ResDef( DBT_libsec_errors_25, 2025, "SEC_ERROR_FILING_KEY: Error re-filing the key for this certificate." )
        ResDef( DBT_libsec_errors_26, 2026, "SEC_ERROR_NO_KEY: The private key for this certificate cannot be found in key database." )
        ResDef( DBT_libsec_errors_27, 2027, "SEC_ERROR_CERT_VALID: This certificate is valid." )
        ResDef( DBT_libsec_errors_28, 2028, "SEC_ERROR_CERT_NOT_VALID: This certificate is not valid." )
        ResDef( DBT_libsec_errors_29, 2029, "SEC_ERROR_CERT_NO_RESPONSE: No Response." )
        ResDef( DBT_libsec_errors_30, 2030, "SEC_ERROR_EXPIRED_ISSUER_CERTIFICATE: The certificate issuer's certificate has expired (check your system date and time)." )
        ResDef( DBT_libsec_errors_31, 2031, "SEC_ERROR_CRL_EXPIRED: The CRL for the certificate's issuer has expired (update it or check your system data and time)." )
        ResDef( DBT_libsec_errors_32, 2032, "SEC_ERROR_CRL_BAD_SIGNATURE: The CRL for the certificate's issuer has an invalid signature." )
        ResDef( DBT_libsec_errors_33, 2033, "SEC_ERROR_CRL_INVALID: New CRL has an invalid format." )
        ResDef( DBT_libsec_errors_34, 2034, "SEC_ERROR_EXTENSION_VALUE_INVALID: Certificate extension value is invalid." )
        ResDef( DBT_libsec_errors_35, 2035, "SEC_ERROR_EXTENSION_NOT_FOUND: Certificate extension not found." )
        ResDef( DBT_libsec_errors_36, 2036, "SEC_ERROR_CA_CERT_INVALID: Issuer certificate is invalid." )
        ResDef( DBT_libsec_errors_37, 2037, "SEC_ERROR_PATH_LEN_CONSTRAINT_INVALID: Certificate path length constraint is invalid." )
        ResDef( DBT_libsec_errors_38, 2038, "SEC_ERROR_CERT_USAGES_INVALID: Certificate usages field is invalid." )
        ResDef( DBT_libsec_errors_39, 2039, "SEC_INTERNAL_ONLY: **Internal ONLY module**" )
        ResDef( DBT_libsec_errors_40, 2040, "SEC_ERROR_INVALID_KEY: The key does not support the requested operation." )
        ResDef( DBT_libsec_errors_41, 2041, "SEC_ERROR_UNKNOWN_CRITICAL_EXTENSION: Certificate contains unknown critical extension." )
        ResDef( DBT_libsec_errors_42, 2042, "SEC_ERROR_OLD_CRL: New CRL is not later than the current one." )
        ResDef( DBT_libsec_errors_43, 2043, "SEC_ERROR_NO_EMAIL_CERT: Not encrypted or signed: You do not yet have an email certificate." )
        ResDef( DBT_libsec_errors_44, 2044, "SEC_ERROR_NO_RECIPIENT_CERTS_QUERY: Not encrypted: You do not have certificates for each of the recipients." )
        ResDef( DBT_libsec_errors_45, 2045, "SEC_ERROR_NOT_A_RECIPIENT: Cannot decrypt: You are not a recipient, or matching certificate and private key not found." )
        ResDef( DBT_libsec_errors_46, 2046, "SEC_ERROR_PKCS7_KEYALG_MISMATCH: Cannot decrypt: Key encryption algorithm does not match your certificate." )
        ResDef( DBT_libsec_errors_47, 2047, "SEC_ERROR_PKCS7_BAD_SIGNATURE: Signature verification failed: No signer found, too many signers found, or improper or corrupted data." )
        ResDef( DBT_libsec_errors_48, 2048, "SEC_ERROR_UNSUPPORTED_KEYALG: Unsupported or unknown key algorithm." )
        ResDef( DBT_libsec_errors_49, 2049, "SEC_ERROR_DECRYPTION_DISALLOWED: Cannot decrypt: Encrypted using a disallowed algorithm or key size." )
        ResDef( DBT_libsec_errors_50, 2050, "XP_LIBSEC_FORTEZZA_BAD_CARD: Fortezza card has not been properly initialized.  Please remove it and return it to your issuer." )
        ResDef( DBT_libsec_errors_51, 2051, "XP_LIBSEC_FORTEZZA_NO_CARD: No Fortezza cards Found." )
        ResDef( DBT_libsec_errors_52, 2052, "XP_LIBSEC_FORTEZZA_NONE_SELECTED: No Fortezza card selected." )
        ResDef( DBT_libsec_errors_53, 2053, "XP_LIBSEC_FORTEZZA_MORE_INFO: Please select a personality to get more info on." )
        ResDef( DBT_libsec_errors_54, 2054, "XP_LIBSEC_FORTEZZA_PERSON_NOT_FOUND: Personality not found." )
        ResDef( DBT_libsec_errors_55, 2055, "XP_LIBSEC_FORTEZZA_NO_MORE_INFO: No more information on that Personality." )
        ResDef( DBT_libsec_errors_56, 2056, "XP_LIBSEC_FORTEZZA_BAD_PIN: Invalid PIN." )
        ResDef( DBT_libsec_errors_57, 2057, "XP_LIBSEC_FORTEZZA_PERSON_ERROR: Couldn't initialize Fortezza personalities." )
        ResDef( DBT_libsec_errors_58, 2058, "SEC_ERROR_NO_KRL: No KRL for this site's certificate has been found." )
        ResDef( DBT_libsec_errors_59, 2059, "SEC_ERROR_KRL_EXPIRED: The KRL for this site's certificate has expired." )
        ResDef( DBT_libsec_errors_60, 2060, "SEC_ERROR_KRL_BAD_SIGNATURE: The KRL for this site's certificate has an invalid signature." )
        ResDef( DBT_libsec_errors_61, 2061, "SEC_ERROR_REVOKED_KEY: The key for this site's certificate has been revoked." )
        ResDef( DBT_libsec_errors_62, 2062, "SEC_ERROR_KRL_INVALID: New KRL has an invalid format." )
        ResDef( DBT_libsec_errors_63, 2063, "SEC_ERROR_NEED_RANDOM: Need random data." )
        ResDef( DBT_libsec_errors_64, 2064, "SEC_ERROR_NO_MODULE: No security module can perform the requested operation." )
        ResDef( DBT_libsec_errors_65, 2065, "SEC_ERROR_NO_TOKEN: The security card or token does not exist, needs to be initialized, or has been removed." )
        ResDef( DBT_libsec_errors_66, 2066, "SEC_ERROR_READ_ONLY: Read-only database." )
        ResDef( DBT_libsec_errors_67, 2067, "SEC_ERROR_NO_SLOT_SELECTED: No slot or token was selected." )
        ResDef( DBT_libsec_errors_68, 2068, "SEC_ERROR_CERT_NICKNAME_COLLISION: A certificate with the same nickname already exists." )
        ResDef( DBT_libsec_errors_69, 2069, "SEC_ERROR_KEY_NICKNAME_COLLISION: A key with the same nickname already exists." )
        ResDef( DBT_libsec_errors_70, 2070, "SEC_ERROR_SAFE_NOT_CREATED: Error while creating safe object." )
        ResDef( DBT_libsec_errors_71, 2071, "SEC_ERROR_BAGGAGE_NOT_CREATED: Error while creating baggage object." )
        ResDef( DBT_libsec_errors_72, 2072, "XP_JAVA_REMOVE_PRINCIPAL_ERROR: Couldn't remove the principal." )
        ResDef( DBT_libsec_errors_73, 2073, "XP_JAVA_DELETE_PRIVILEGE_ERROR: Couldn't delete the privilege." )
        ResDef( DBT_libsec_errors_74, 2074, "XP_JAVA_CERT_NOT_EXISTS_ERROR: This principal doesn't have a certificate." )
        ResDef( DBT_libsec_errors_75, 2075, "SEC_ERROR_BAD_EXPORT_ALGORITHM: Required algorithm is not allowed." )
        ResDef( DBT_libsec_errors_76, 2076, "SEC_ERROR_EXPORTING_CERTIFICATES: Error attempting to export certificates." )
        ResDef( DBT_libsec_errors_77, 2077, "SEC_ERROR_IMPORTING_CERTIFICATES: Error attempting to import certificates." )
        ResDef( DBT_libsec_errors_78, 2078, "SEC_ERROR_PKCS12_DECODING_PFX: Unable to import.  Decoding error.  File not valid." )
        ResDef( DBT_libsec_errors_79, 2079, "SEC_ERROR_PKCS12_INVALID_MAC: Unable to import.  Invalid MAC.  Incorrect password or corrupt file." )
        ResDef( DBT_libsec_errors_80, 2080, "SEC_ERROR_PKCS12_UNSUPPORTED_MAC_ALGORITHM: Unable to import.  MAC algorithm not supported." )
        ResDef( DBT_libsec_errors_81, 2081, "SEC_ERROR_PKCS12_UNSUPPORTED_TRANSPORT_MODE: Unable to import." )
        ResDef( DBT_libsec_errors_82, 2082, "SEC_ERROR_PKCS12_CORRUPT_PFX_STRUCTURE: Unable to import.  File structure is corrupt." )
        ResDef( DBT_libsec_errors_83, 2083, "SEC_ERROR_PKCS12_UNSUPPORTED_PBE_ALGORITHM: Unable to import.  Encryption algorithm not supported." )
        ResDef( DBT_libsec_errors_84, 2084, "SEC_ERROR_PKCS12_UNSUPPORTED_VERSION: Unable to import.  File version not supported." )
        ResDef( DBT_libsec_errors_85, 2085, "SEC_ERROR_PKCS12_PRIVACY_PASSWORD_INCORRECT: Unable to import. Incorrect privacy password." )
        ResDef( DBT_libsec_errors_86, 2086, "SEC_ERROR_PKCS12_CERT_COLLISION: Unable to import.  Same nickname already exists in database." )
        ResDef( DBT_libsec_errors_87, 2087, "SEC_ERROR_USER_CANCELLED: The user pressed cancel." )
        ResDef( DBT_libsec_errors_88, 2088, "SEC_ERROR_PKCS12_DUPLICATE_DATA: Not imported, already in database." )
        ResDef( DBT_libsec_errors_89, 2089, "SEC_ERROR_MESSAGE_SEND_ABORTED: Message not sent." )
        ResDef( DBT_libsec_errors_90, 2090, "SEC_ERROR_INADEQUATE_KEY_USAGE: Certificate key usage inadequate for attempted operation." )
        ResDef( DBT_libsec_errors_91, 2091, "SEC_ERROR_INADEQUATE_CERT_TYPE: Certificate type not approved for application." )
        ResDef( DBT_libsec_errors_92, 2092, "SEC_ERROR_CERT_ADDR_MISMATCH: Address in signing certificate does not match address in message headers." )
        ResDef( DBT_libsec_errors_93, 2093, "SEC_ERROR_PKCS12_UNABLE_TO_IMPORT_KEY: Unable to import.  Error attempting to import private key." )
        ResDef( DBT_libsec_errors_94, 2094, "SEC_ERROR_PKCS12_IMPORTING_CERT_CHAIN: Unable to import.  Error attempting to import certificate chain." )
        ResDef( DBT_libsec_errors_95, 2095, "SEC_ERROR_PKCS12_UNABLE_TO_LOCATE_OBJECT_BY_NAME: Unable to export.  Unable to locate certificate or key by nickname." )
        ResDef( DBT_libsec_errors_96, 2096, "SEC_ERROR_PKCS12_UNABLE_TO_EXPORT_KEY: Unable to export.  Private Key could not be located and exported." )
        ResDef( DBT_libsec_errors_97, 2097, "SEC_ERROR_PKCS12_UNABLE_TO_WRITE: Unable to export.  Unable to write the export file." )
        ResDef( DBT_libsec_errors_98, 2098, "SEC_ERROR_PKCS12_UNABLE_TO_READ: Unable to import.  Unable to read the import file." )
        ResDef( DBT_libsec_errors_99, 2099, "SEC_ERROR_PKCS12_KEY_DATABASE_NOT_INITIALIZED: Unable to export.  Key database corrupt or deleted." )
        ResDef( DBT_libsec_errors_100, 2100, "SEC_ERROR_KEYGEN_FAIL: Unable to generate public/private key pair." )
        ResDef( DBT_libsec_errors_101, 2101, "SEC_ERROR_INVALID_PASSWORD: Password entered is invalid." )
        ResDef( DBT_libsec_errors_102, 2102, "SEC_ERROR_RETRY_OLD_PASSWORD: Old password entered incorrectly.  Please try again." )
        ResDef( DBT_libsec_errors_103, 2103, "SEC_ERROR_BAD_NICKNAME: Certificate nickname already in use." )
        ResDef( DBT_libsec_errors_104, 2104, "SEC_ERROR_NOT_FORTEZZA_ISSUER: Peer FORTEZZA chain has a non-FORTEZZA Certificate." )
        ResDef( DBT_libsec_errors_105, 2105, "SEC_ERROR_CANNOT_MOVE_SENSITIVE_KEY: A sensitive key cannot be moved to the slot where it is needed." )
        ResDef( DBT_libsec_errors_106, 2106, "SEC_ERROR_JS_INVALID_MODULE_NAME: Invalid module name." )
        ResDef( DBT_libsec_errors_107, 2107, "SEC_ERROR_JS_INVALID_DLL: Invalid module path/filename." )
        ResDef( DBT_libsec_errors_108, 2108, "SEC_ERROR_JS_ADD_MOD_FAILURE: Unable to add module." )
        ResDef( DBT_libsec_errors_109, 2109, "SEC_ERROR_JS_DEL_MOD_FAILURE: Unable to delete module." )
        ResDef( DBT_libsec_errors_110, 2110, "SEC_ERROR_OLD_KRL: New KRL is not later than the current one." )
        ResDef( DBT_libsec_errors_111, 2111, "SEC_ERROR_CKL_CONFLICT: New CKL has different issuer than current CKL.  Delete current CKL." )
        ResDef( DBT_libsec_errors_112, 2112, "SEC_ERROR_CERT_NOT_IN_NAME_SPACE: The Certifying Authority for this certificate is not permitted to issue a certificate with this name." )
        ResDef( DBT_libsec_errors_113, 2113, "SEC_ERROR_KRL_NOT_YET_VALID: The KRL for this certificate is not yet valid." )
        ResDef( DBT_libsec_errors_114, 2114, "SEC_ERROR_CRL_NOT_YET_VALID: The CRL for this certificate is not yet valid." )
        ResDef( DBT_libsec_errors_115, 2115, "SEC_ERROR_UNKNOWN_CERT: The requested certificate could not be found." )
        ResDef( DBT_libsec_errors_116, 2116, "SEC_ERROR_UNKNOWN_SIGNER: The signer's certificate could not be found." )
        ResDef( DBT_libsec_errors_117, 2117, "SEC_ERROR_CERT_BAD_ACCESS_LOCATION: The location for the certificate status server has invalid format." )
        ResDef( DBT_libsec_errors_118, 2118, "SEC_ERROR_OCSP_UNKNOWN_RESPONSE_TYPE: The OCSP response cannot be fully decoded, it is of an unknown type." )
        ResDef( DBT_libsec_errors_119, 2119, "SEC_ERROR_OCSP_BAD_HTTP_RESPONSE: The OCSP server returned unexpected/invalid HTTP data." )
        ResDef( DBT_libsec_errors_120, 2120, "SEC_ERROR_OCSP_MALFORMED_REQUEST: The OCSP server found the request to be corrupted or improperly formed." )
        ResDef( DBT_libsec_errors_121, 2121, "SEC_ERROR_OCSP_SERVER_ERROR: The OCSP server experienced an internal error." )
        ResDef( DBT_libsec_errors_122, 2122, "SEC_ERROR_OCSP_TRY_SERVER_LATER: The OCSP server suggests trying again later." )
        ResDef( DBT_libsec_errors_123, 2123, "SEC_ERROR_OCSP_REQUEST_NEEDS_SIG: The OCSP server requires a signature on this request." )
        ResDef( DBT_libsec_errors_124, 2124, "SEC_ERROR_OCSP_UNAUTHORIZED_REQUEST: The OCSP server has refused this request as unauthorized." )
        ResDef( DBT_libsec_errors_125, 2125, "SEC_ERROR_OCSP_UNKNOWN_RESPONSE_STATUS: The OCSP server returned an unrecognizable status." )
        ResDef( DBT_libsec_errors_126, 2126, "SEC_ERROR_OCSP_UNKNOWN_CERT: The OCSP server has no status for the certificate." )
        ResDef( DBT_libsec_errors_127, 2127, "SEC_ERROR_OCSP_NOT_ENABLED: OCSP is not enabled." )
        ResDef( DBT_libsec_errors_128, 2128, "SEC_ERROR_OCSP_NO_DEFAULT_RESPONDER: OCSP responder not set." )
        ResDef( DBT_libsec_errors_129, 2129, "SEC_ERROR_OCSP_MALFORMED_RESPONSE: Response from OCSP server was corrupted or improperly formed." )
        ResDef( DBT_libsec_errors_130, 2130, "SEC_ERROR_OCSP_UNAUTHORIZED_RESPONSE: The signer of the OCSP response is not authorized to give status for this certificate." )
        ResDef( DBT_libsec_errors_131, 2131, "SEC_ERROR_OCSP_FUTURE_RESPONSE: The OCSP response is not yet valid (contains a date in the future)." )
        ResDef( DBT_libsec_errors_132, 2132, "SEC_ERROR_OCSP_OLD_RESPONSE: The OCSP response contains out of date information." )
        ResDef( DBT_libsec_errors_133, 2133, "SEC_ERROR_DIGEST_NOT_FOUND: The CMS or PKCS#7 digest was not found in signed message." )
        ResDef( DBT_libsec_errors_134, 2134, "SEC_ERROR_UNSUPPORTED_MESSAGE_TYPE: The CMS or PKCS#7 message type is unsupported." )
        ResDef( DBT_libsec_errors_135, 2135, "SEC_ERROR_MODULE_STUCK: PKCS#11 module could not be removed because it is still in use." )
        ResDef( DBT_libsec_errors_136, 2136, "SEC_ERROR_BAD_TEMPLATE: Could not decode ASN.1 data, specified template is invalid." )
        ResDef( DBT_libsec_errors_137, 2137, "SEC_ERROR_CRL_NOT_FOUND: No matching CRL was found." )
        ResDef( DBT_libsec_errors_138, 2138, "SEC_ERROR_REUSED_ISSUER_AND_SERIAL: Attempting to import a cert which conflicts with issuer/serial of existing cert." )
        ResDef( DBT_libsec_errors_139, 2139, "SEC_ERROR_BUSY: NSS cannot shut down, objects are still in use." )
        ResDef( DBT_libsec_errors_140, 2140, "SEC_ERROR_EXTRA_INPUT: DER-encoded message contains extra unused data." )
        ResDef( DBT_libsec_errors_141, 2141, "SEC_ERROR_UNSUPPORTED_ELLIPTIC_CURVE: Unsupported elliptic curve." )
        ResDef( DBT_libsec_errors_142, 2142, "SEC_ERROR_UNSUPPORTED_EC_POINT_FORM: Unsupported elliptic curve point form." )
        ResDef( DBT_libsec_errors_143, 2143, "SEC_ERROR_UNRECOGNIZED_OID: Unrecognized Object Identifier." )
        ResDef( DBT_libsec_errors_144, 2144, "SEC_ERROR_OCSP_INVALID_SIGNING_CERT: Invalid OCSP signing certificate in response." )
        ResDef( DBT_libsec_errors_145, 2145, "SEC_ERROR_REVOKED_CERTIFICATE_CRL: Certificate is revoked in issuer's CRL." )
        ResDef( DBT_libsec_errors_146, 2146, "SEC_ERROR_REVOKED_CERTIFICATE_OCSP: Issuer's OCSP reports certificate is revoked." )
        ResDef( DBT_libsec_errors_147, 2147, "SEC_ERROR_CRL_INVALID_VERSION: Issuer's CRL has unknown version number." )
        ResDef( DBT_libsec_errors_148, 2148, "SEC_ERROR_CRL_V1_CRITICAL_EXTENSION: Issuer's v1 CRL has a critical extension." )
        ResDef( DBT_libsec_errors_149, 2149, "SEC_ERROR_CRL_UNKNOWN_CRITICAL_EXTENSION: Issuer's v2 CRL has an unknown critical extension." )
        /* Refer http://mxr.mozilla.org/security/source/security/nss/cmd/lib/SECerrs.h#499 */
        ResDef( DBT_libsec_errors_150, 2150, "SEC_ERROR_UNKNOWN_OBJECT_TYPE: Unknown object type specified." )
        ResDef( DBT_libsec_errors_151, 2151, "SEC_ERROR_INCOMPATIBLE_PKCS11: PKCS #11 driver violates the spec in an incompatible way." )
        ResDef( DBT_libsec_errors_152, 2152, "SEC_ERROR_NO_EVENT: No new slot event is available at this time." )
        ResDef( DBT_libsec_errors_153, 2153, "SEC_ERROR_CRL_ALREADY_EXISTS: CRL already exists." )

        ResDef( DBT_libsec_errors_154, 2154, "SEC_ERROR_NOT_INITIALIZED: NSS is not initialized." )
        ResDef( DBT_libsec_errors_155, 2155, "SEC_ERROR_TOKEN_NOT_LOGGED_IN: The operation failed because the PKCS#11 token is not logged in." )
        ResDef( DBT_libsec_errors_156, 2156, "SEC_ERROR_OCSP_RESPONDER_CERT_INVALID: Configured OCSP responder's certificate is invalid." )
        ResDef( DBT_libsec_errors_157, 2157, "SEC_ERROR_OCSP_BAD_SIGNATURE: OCSP response has an invalid signature." )

        ResDef( DBT_libsec_errors_158, 2158, "SEC_ERROR_OUT_OF_SEARCH_LIMITS: Cert validation search is out of search limits" )
        ResDef( DBT_libsec_errors_159, 2159, "SEC_ERROR_INVALID_POLICY_MAPPING: Policy mapping contains anypolicy" )
        ResDef( DBT_libsec_errors_160, 2160, "SEC_ERROR_POLICY_VALIDATION_FAILED: Cert chain fails policy validation" )
        ResDef( DBT_libsec_errors_161, 2161, "SEC_ERROR_UNKNOWN_AIA_LOCATION_TYPE: Unknown location type in cert AIA extension" )
        ResDef( DBT_libsec_errors_162, 2162, "SEC_ERROR_BAD_HTTP_RESPONSE: Server returned bad HTTP response" )
        ResDef( DBT_libsec_errors_163, 2163, "SEC_ERROR_BAD_LDAP_RESPONSE: Server returned bad LDAP response" )
        ResDef( DBT_libsec_errors_164, 2164, "SEC_ERROR_FAILED_TO_ENCODE_DATA: Failed to encode data with ASN1 encoder" )
        ResDef( DBT_libsec_errors_165, 2165, "SEC_ERROR_BAD_INFO_ACCESS_LOCATION: Bad information access location in cert extension" )
        ResDef( DBT_libsec_errors_166, 2166, "SEC_ERROR_LIBPKIX_INTERNAL: Libpkix internal error occured during cert validation." )
        ResDef( DBT_libsec_errors_167, 2167, "SEC_ERROR_PKCS11_GENERAL_ERROR: PKCS11  general error occured during cert validation." )
        ResDef( DBT_libsec_errors_168, 2168, "SEC_ERROR_PKCS11_FUNCTION_FAILED: PKCS11 function failed." )
        ResDef( DBT_libsec_errors_169, 2169, "SEC_ERROR_PKCS11_DEVICE_ERROR: PKCS11 device  error." )
        ResDef( DBT_libsec_errors_170, 2170, "SEC_ERROR_BAD_INFO_ACCESS_METHOD: Bad access info." )
        ResDef( DBT_libsec_errors_171, 2171, "SEC_ERROR_CRL_IMPORT_FAILED: CRL import failed." )
     
        /* DBT_libssl_errors: http://www.mozilla.org/projects/security/pki/nss/ref/ssl/sslerr.html */
        ResDef( DBT_libssl_errors_0, 3000, "SSL_ERROR_EXPORT_ONLY_SERVER: Client does not support high-grade encryption." )
        ResDef( DBT_libssl_errors_1, 3001, "SSL_ERROR_US_ONLY_SERVER: Client requires high-grade encryption which is not supported." )
        ResDef( DBT_libssl_errors_2, 3002, "SSL_ERROR_NO_CYPHER_OVERLAP: No common encryption algorithm(s) with client." )
        ResDef( DBT_libssl_errors_3, 3003, "SSL_ERROR_NO_CERTIFICATE: Unable to find the certificate or key necessary for authentication." )
        ResDef( DBT_libssl_errors_4, 3004, "SSL_ERROR_BAD_CERTIFICATE: Unable to communicate securely: Client certificate was rejected." )
        ResDef( DBT_libssl_errors_5, 3005, "libssl error 5 (unused error)" )
        ResDef( DBT_libssl_errors_6, 3006, "SSL_ERROR_BAD_CLIENT: Invalid data read from client." )
        ResDef( DBT_libssl_errors_7, 3007, "SSL_ERROR_BAD_SERVER: Invalid data read from server (only applicable on client side)." )
        ResDef( DBT_libssl_errors_8, 3008, "SSL_ERROR_UNSUPPORTED_CERTIFICATE_TYPE: Unsupported certificate type." )
        ResDef( DBT_libssl_errors_9, 3009, "SSL_ERROR_UNSUPPORTED_VERSION: Client is using unsupported SSL version." )
        ResDef( DBT_libssl_errors_10, 3010, "libssl error 10 (unused error)" )
        ResDef( DBT_libssl_errors_11, 3011, "SSL_ERROR_WRONG_CERTIFICATE: Public key in the server's own certificate does not match its private key." )
        ResDef( DBT_libssl_errors_12, 3012, "SSL_ERROR_BAD_CERT_DOMAIN: Requested domain name does not match the server's certificate." )
        ResDef( DBT_libssl_errors_13, 3013, "SSL_ERROR_POST_WARNING (unused error)" )
        ResDef( DBT_libssl_errors_14, 3014, "SSL_ERROR_SSL2_DISABLED: Client only supports SSL version 2, which is disabled." )
        ResDef( DBT_libssl_errors_15, 3015, "SSL_ERROR_BAD_MAC_READ: Server has received a record with an incorrect Message Authentication Code." )
        ResDef( DBT_libssl_errors_16, 3016, "SSL_ERROR_BAD_MAC_ALERT: Client indicated receiving record with an incorrect Message Authentication Code." )
        ResDef( DBT_libssl_errors_17, 3017, "SSL_ERROR_BAD_CERT_ALERT: Client indicated it cannot verify server certificate." )
        ResDef( DBT_libssl_errors_18, 3018, "SSL_ERROR_REVOKED_CERT_ALERT: Client has rejected server certificate as revoked." )
        ResDef( DBT_libssl_errors_19, 3019, "SSL_ERROR_EXPIRED_CERT_ALERT: Client has rejected server certificate as expired." )
        ResDef( DBT_libssl_errors_20, 3020, "SSL_ERROR_SSL_DISABLED: Cannot connect: SSL is disabled." )
        ResDef( DBT_libssl_errors_21, 3021, "SSL_ERROR_FORTEZZA_PQG: Cannot connect: Client is in another Fortezza domain (unused error)." )
        ResDef( DBT_libssl_errors_22, 3022, "SSL_ERROR_UNKNOWN_CIPHER_SUITE: An unknown SSL cipher suite has been requested." )
        ResDef( DBT_libssl_errors_23, 3023, "SSL_ERROR_NO_CIPHERS_SUPPORTED: No cipher suites are present and enabled." )
        ResDef( DBT_libssl_errors_24, 3024, "SSL_ERROR_BAD_BLOCK_PADDING: Server received a record with bad block padding." )
        ResDef( DBT_libssl_errors_25, 3025, "SSL_ERROR_RX_RECORD_TOO_LONG: Server received a record that exceeded the maximum permissible length." )
        ResDef( DBT_libssl_errors_26, 3026, "SSL_ERROR_TX_RECORD_TOO_LONG: Server attempted to send a record that exceeded the maximum permissible length." )
        ResDef( DBT_libssl_errors_27, 3027, "SSL_ERROR_RX_MALFORMED_HELLO_REQUEST: Malformed Hello Request handshake message." )
        ResDef( DBT_libssl_errors_28, 3028, "SSL_ERROR_RX_MALFORMED_CLIENT_HELLO: Malformed Client Hello handshake message." )
        ResDef( DBT_libssl_errors_29, 3029, "SSL_ERROR_RX_MALFORMED_SERVER_HELLO: Malformed Server Hello handshake message." )
        ResDef( DBT_libssl_errors_30, 3030, "SSL_ERROR_RX_MALFORMED_CERTIFICATE: Malformed Certificate handshake message." )
        ResDef( DBT_libssl_errors_31, 3031, "SSL_ERROR_RX_MALFORMED_SERVER_KEY_EXCH: Malformed Server Key Exchange handshake message." )
        ResDef( DBT_libssl_errors_32, 3032, "SSL_ERROR_RX_MALFORMED_CERT_REQUEST: Malformed Certificate Request handshake message." )
        ResDef( DBT_libssl_errors_33, 3033, "SSL_ERROR_RX_MALFORMED_HELLO_DONE: Malformed Server Hello Done handshake message." )
        ResDef( DBT_libssl_errors_34, 3034, "SSL_ERROR_RX_MALFORMED_CERT_VERIFY: Malformed Certificate Verify handshake message." )
        ResDef( DBT_libssl_errors_35, 3035, "SSL_ERROR_RX_MALFORMED_CLIENT_KEY_EXCH: Malformed Client Key Exchange handshake message." )
        ResDef( DBT_libssl_errors_36, 3036, "SSL_ERROR_RX_MALFORMED_FINISHED: Malformed Finished handshake message." )
        ResDef( DBT_libssl_errors_37, 3037, "SSL_ERROR_RX_MALFORMED_CHANGE_CIPHER: Malformed Change Cipher Spec record." )
        ResDef( DBT_libssl_errors_38, 3038, "SSL_ERROR_RX_MALFORMED_ALERT: Malformed Alert record." )
        ResDef( DBT_libssl_errors_39, 3039, "SSL_ERROR_RX_MALFORMED_HANDSHAKE: Malformed Handshake record." )
        ResDef( DBT_libssl_errors_40, 3040, "SSL_ERROR_RX_MALFORMED_APPLICATION_DATA: Malformed Application Data record." )
        ResDef( DBT_libssl_errors_41, 3041, "SSL_ERROR_RX_UNEXPECTED_HELLO_REQUEST: Unexpected Hello Request handshake message." )
        ResDef( DBT_libssl_errors_42, 3042, "SSL_ERROR_RX_UNEXPECTED_CLIENT_HELLO: Unexpected Client Hello handshake message." )
        ResDef( DBT_libssl_errors_43, 3043, "SSL_ERROR_RX_UNEXPECTED_SERVER_HELLO: Unexpected Server Hello handshake message." )
        ResDef( DBT_libssl_errors_44, 3044, "SSL_ERROR_RX_UNEXPECTED_CERTIFICATE: Unexpected Certificate handshake message." )
        ResDef( DBT_libssl_errors_45, 3045, "SSL_ERROR_RX_UNEXPECTED_SERVER_KEY_EXCH: Unexpected Server Key Exchange handshake message." )
        ResDef( DBT_libssl_errors_46, 3046, "SSL_ERROR_RX_UNEXPECTED_CERT_REQUEST: Unexpected Certificate Request handshake message." )
        ResDef( DBT_libssl_errors_47, 3047, "SSL_ERROR_RX_UNEXPECTED_HELLO_DONE: Unexpected Server Hello Done handshake message." )
        ResDef( DBT_libssl_errors_48, 3048, "SSL_ERROR_RX_UNEXPECTED_CERT_VERIFY: Unexpected Certificate Verify handshake message." )
        ResDef( DBT_libssl_errors_49, 3049, "SSL_ERROR_RX_UNEXPECTED_CLIENT_KEY_EXCH: Unexpected Client Key Exchange handshake message." )
        ResDef( DBT_libssl_errors_50, 3050, "SSL_ERROR_RX_UNEXPECTED_FINISHED: Unexpected Finished handshake message." )
        ResDef( DBT_libssl_errors_51, 3051, "SSL_ERROR_RX_UNEXPECTED_CHANGE_CIPHER: Unexpected Change Cipher Spec record." )
        ResDef( DBT_libssl_errors_52, 3052, "SSL_ERROR_RX_UNEXPECTED_ALERT: Unexpected Alert record." )
        ResDef( DBT_libssl_errors_53, 3053, "SSL_ERROR_RX_UNEXPECTED_HANDSHAKE: Unexpected Handshake record." )
        ResDef( DBT_libssl_errors_54, 3054, "SSL_ERROR_RX_UNEXPECTED_APPLICATION_DATA: Unexpected Application Data record." )
        ResDef( DBT_libssl_errors_55, 3055, "SSL_ERROR_RX_UNKNOWN_RECORD_TYPE: Server received a record with an unknown content type." )
        ResDef( DBT_libssl_errors_56, 3056, "SSL_ERROR_RX_UNKNOWN_HANDSHAKE: Server received a handshake message with an unknown message type." )
        ResDef( DBT_libssl_errors_57, 3057, "SSL_ERROR_RX_UNKNOWN_ALERT: Server received an alert record with an unknown alert description." )
        ResDef( DBT_libssl_errors_58, 3058, "SSL_ERROR_CLOSE_NOTIFY_ALERT: Client has closed the connection." )
        ResDef( DBT_libssl_errors_59, 3059, "SSL_ERROR_HANDSHAKE_UNEXPECTED_ALERT: Client was not expecting a handshake message it received." )
        ResDef( DBT_libssl_errors_60, 3060, "SSL_ERROR_DECOMPRESSION_FAILURE_ALERT: Client was unable to successfully decompress an SSL record it received." )
        ResDef( DBT_libssl_errors_61, 3061, "SSL_ERROR_HANDSHAKE_FAILURE_ALERT: Client was unable to negotiate an acceptable set of security parameters." )
        ResDef( DBT_libssl_errors_62, 3062, "SSL_ERROR_ILLEGAL_PARAMETER_ALERT: Client rejected a handshake message for unacceptable content." )
        ResDef( DBT_libssl_errors_63, 3063, "SSL_ERROR_UNSUPPORTED_CERT_ALERT: Client does not support certificates of the type it received." )
        ResDef( DBT_libssl_errors_64, 3064, "SSL_ERROR_CERTIFICATE_UNKNOWN_ALERT: Client had some unspecified issue with the certificate it received." )
        ResDef( DBT_libssl_errors_65, 3065, "SSL_ERROR_GENERATE_RANDOM_FAILURE: Failure of random number generator." )
        ResDef( DBT_libssl_errors_66, 3066, "SSL_ERROR_SIGN_HASHES_FAILURE: Unable to digitally sign data required to verify certificate." )
        ResDef( DBT_libssl_errors_67, 3067, "SSL_ERROR_EXTRACT_PUBLIC_KEY_FAILURE: Unable to extract the public key from client certificate." )
        ResDef( DBT_libssl_errors_68, 3068, "SSL_ERROR_SERVER_KEY_EXCHANGE_FAILURE: Unspecified failure while processing SSL Server Key Exchange handshake." )
        ResDef( DBT_libssl_errors_69, 3069, "SSL_ERROR_CLIENT_KEY_EXCHANGE_FAILURE: Unspecified failure while processing SSL Client Key Exchange handshake." )
        ResDef( DBT_libssl_errors_70, 3070, "SSL_ERROR_ENCRYPTION_FAILURE: Bulk data encryption algorithm failed in selected cipher suite." )
        ResDef( DBT_libssl_errors_71, 3071, "SSL_ERROR_DECRYPTION_FAILURE: Bulk data decryption algorithm failed in selected cipher suite." )
        ResDef( DBT_libssl_errors_72, 3072, "SSL_ERROR_SOCKET_WRITE_FAILURE: Attempt to write encrypted data to underlying socket failed." )
        ResDef( DBT_libssl_errors_73, 3073, "SSL_ERROR_MD5_DIGEST_FAILURE: MD5 digest function failed." )
        ResDef( DBT_libssl_errors_74, 3074, "SSL_ERROR_SHA_DIGEST_FAILURE: SHA-1 digest function failed." )
        ResDef( DBT_libssl_errors_75, 3075, "SSL_ERROR_MAC_COMPUTATION_FAILURE: MAC computation failed." )
        ResDef( DBT_libssl_errors_76, 3076, "SSL_ERROR_SYM_KEY_CONTEXT_FAILURE: Failure to create Symmetric Key context." )
        ResDef( DBT_libssl_errors_77, 3077, "SSL_ERROR_SYM_KEY_UNWRAP_FAILURE: Failure to unwrap the Symmetric key in Client Key Exchange message." )
        ResDef( DBT_libssl_errors_78, 3078, "SSL_ERROR_PUB_KEY_SIZE_LIMIT_EXCEEDED: Internal error: Server attempted to use domestic-grade public key with export cipher suite." )

        ResDef( DBT_libssl_errors_79, 3079, "SSL_ERROR_IV_PARAM_FAILURE: PKCS #11 code failed to translate an IV into a param." )
        ResDef( DBT_libssl_errors_80, 3080, "SSL_ERROR_INIT_CIPHER_SUITE_FAILURE: Failed to initialize the selected cipher suite." )
        ResDef( DBT_libssl_errors_81, 3081, "SSL_ERROR_SESSION_KEY_GEN_FAILURE: Failed to generate session keys for SSL session." )
        ResDef( DBT_libssl_errors_82, 3082, "SSL_ERROR_NO_SERVER_KEY_FOR_ALG: Server has no key for the attempted key exchange algorithm." )
        ResDef( DBT_libssl_errors_83, 3083, "SSL_ERROR_TOKEN_INSERTION_REMOVAL: PKCS #11 token was inserted or removed while operation was in progress." )
        ResDef( DBT_libssl_errors_84, 3084, "SSL_ERROR_TOKEN_SLOT_NOT_FOUND: No PKCS #11 token could be found to do a required operation." )
        ResDef( DBT_libssl_errors_85, 3085, "SSL_ERROR_NO_COMPRESSION_OVERLAP: Cannot communicate securely with peer: No common compression algorithm(s)." )
        ResDef( DBT_libssl_errors_86, 3086, "SSL_ERROR_HANDSHAKE_NOT_COMPLETED: Cannot initiate another SSL handshake until current handshake is complete." )
        ResDef( DBT_libssl_errors_87, 3087, "SSL_ERROR_BAD_HANDSHAKE_HASH_VALUE: Received incorrect handshake hash values from peer." )
        ResDef( DBT_libssl_errors_88, 3088, "SSL_ERROR_CERT_KEA_MISMATCH: Certificate provided cannot be used with the selected key exchange algorithm." )
        ResDef( DBT_libssl_errors_89, 3089, "SSL_ERROR_NO_TRUSTED_SSL_CLIENT_CA: Server configuration does not have any certificate authority trusted for SSL client authentication." )
        ResDef( DBT_libssl_errors_90, 3090, "SSL_ERROR_SESSION_NOT_FOUND: Client SSL session ID not found in server session cache." )
        ResDef( DBT_libssl_errors_91, 3091, "SSL_ERROR_DECRYPTION_FAILED_ALERT: Client was unable to decrypt an SSL record it received." )
        ResDef( DBT_libssl_errors_92, 3092, "SSL_ERROR_RECORD_OVERFLOW_ALERT: Client received an SSL record that was longer than permitted." )
        ResDef( DBT_libssl_errors_93, 3093, "SSL_ERROR_UNKNOWN_CA_ALERT: Client does not recognize and trust the CA that issues server certificate." )
        ResDef( DBT_libssl_errors_94, 3094, "SSL_ERROR_ACCESS_DENIED_ALERT: Client received a valid certificate but denied access." )
        ResDef( DBT_libssl_errors_95, 3095, "SSL_ERROR_DECODE_ERROR_ALERT: Client could not decode an SSL handshake message." )
        ResDef( DBT_libssl_errors_96, 3096, "SSL_ERROR_DECRYPT_ERROR_ALERT: Client reports signature verification or key exchange failure." )
        ResDef( DBT_libssl_errors_97, 3097, "SSL_ERROR_EXPORT_RESTRICTION_ALERT: Client reports negotiation not in compliance with export regulations." )
        ResDef( DBT_libssl_errors_98, 3098, "SSL_ERROR_PROTOCOL_VERSION_ALERT: Client reports incompatible or unsupported protocol version." )
        ResDef( DBT_libssl_errors_99, 3099, "SSL_ERROR_INSUFFICIENT_SECURITY_ALERT: Server configuration requires ciphers more secure than those supported by client." )
        ResDef( DBT_libssl_errors_100, 3100, "SSL_ERROR_INTERNAL_ERROR_ALERT: Client reports it experienced an internal error." )
        ResDef( DBT_libssl_errors_101, 3101, "SSL_ERROR_USER_CANCELED_ALERT: Client canceled handshake." )
        ResDef( DBT_libssl_errors_102, 3102, "SSL_ERROR_NO_RENEGOTIATION_ALERT: Client does not permit renegotiation of SSL security parameters." )
        /* Refer http://mxr.mozilla.org/security/source/security/nss/cmd/lib/SSLerrs.h#370 */
        ResDef( DBT_libssl_errors_103, 3103, "SSL_ERROR_SERVER_CACHE_NOT_CONFIGURED: SSL server cache not configured and not disabled for this socket." )
        ResDef( DBT_libssl_errors_104, 3104, "SSL_ERROR_UNSUPPORTED_EXTENSION_ALERT: SSL peer does not support requested TLS hello extension." )
        ResDef( DBT_libssl_errors_105, 3105, "SSL_ERROR_CERTIFICATE_UNOBTAINABLE_ALERT: SSL peer could not obtain your certificate from the supplied URL." )
        ResDef( DBT_libssl_errors_106, 3106, "SSL_ERROR_UNRECOGNIZED_NAME_ALERT: SSL peer has no certificate for the requested DNS name." )
        ResDef( DBT_libssl_errors_107, 3107, "SSL_ERROR_BAD_CERT_STATUS_RESPONSE_ALERT: SSL peer was unable to get an OCSP response for its certificate." )
        ResDef( DBT_libssl_errors_108, 3108, "SSL_ERROR_BAD_CERT_HASH_VALUE_ALERT: SSL peer reported bad certificate hash value." )
        ResDef( DBT_libssl_errors_109, 3109, "SSL_ERROR_RX_UNEXPECTED_NEW_SESSION_TICKET: SSL received an unexpected New Session Ticket handshake message." )
        ResDef( DBT_libssl_errors_110, 3110, "SSL_ERROR_RX_MALFORMED_NEW_SESSION_TICKET: SSL received a malformed New Session Ticket handshake message." )
        ResDef( DBT_libssl_errors_111, 3111, "SSL_ERROR_DECOMPRESSION_FAILURE: SSL decompression failed." )
        ResDef( DBT_libssl_errors_112, 3112, "SSL_ERROR_RENEGOTIATION_NOT_ALLOWED: SSL renegotiation is not allowed." )

END_STR(base)
